#!/bin/bash
# -*- ENCODING: UTF-8 -*-

source /usr/share/idiomind/ifs/c.conf
DSP=$DS/practice
[[ -n "$(ps -A | pgrep -f "$DSP/df.sh")" ]] && killall "$DSP/df.sh" &
[[ -n "$(ps -A | pgrep -f "$DSP/dmc.sh")" ]] && killall "$DSP/dmc.sh" &
[[ -n "$(ps -A | pgrep -f "$DSP/dlw.sh")" ]] && killall "$DSP/dlw.sh" &
[[ -n "$(ps -A | pgrep -f "$DSP/dls.sh")" ]] && killall "$DSP/dls.sh" &
[[ -n "$(ps -A | pgrep -f "$DSP/prct.sh")" ]] && killall "$DSP/prct.sh" &
[[ -n "$(ps -A | pgrep -f "$DSP/strt.sh")" ]] && killall "$DSP/strt.sh" &
[[ -n "$(ps -A | pgrep -f play)" ]] && killall play &
cd "$DC_tlt/practice"

easy=$2
ling=$3
hard=$4
all=$5

if [ "$1" = df ]; then
	rm look_f fin fin1 fin2 fin3 ok.f
	echo "1" > .iconf
	echo "0" > l_f
	$DSP/strt.sh &
	exit 1
elif [ "$1" = dm ]; then
	rm look_mc mcin1 mcin2 mcin3 word1.idx ok.m
	echo "1" > .iconmc
	echo "0" > l_m
	$DSP/strt.sh &
	exit 1
elif [ "$1" = dw ]; then
	rm look_lw lwin lwin1 lwin2 lwin3 ok.w
	echo "1" > .iconlw
	echo "0" > l_w
	$DSP/strt.sh &
	exit 1
elif [ "$1" = ds ]; then
	rm look_ls lsin ok.s
	echo "1" > .iconls
	echo "0" > l_s
	$DSP/strt.sh &
	exit 1
fi
	
if [ "$1" = f ]; then

	cd "$DC_tlt/practice"
	
	[[ -f l_f ]] && echo $(($(cat l_f)+$easy)) > l_f || echo $easy > l_f
	s=$(cat l_f)
	v=$((100*$s/$all))
	if [ $v -le 1 ]; then
		echo 1 > .iconf
	elif [ $v -le 5 ]; then
		echo 2 > .iconf
	elif [ $v -le 10 ]; then
		echo 3 > .iconf
	elif [ $v -le 15 ]; then
		echo 4 > .iconf
	elif [ $v -le 20 ]; then
		echo 5 > .iconf
	elif [ $v -le 25 ]; then
		echo 6 > .iconf
	elif [ $v -le 30 ]; then
		echo 7 > .iconf
	elif [ $v -le 35 ]; then
		echo 8 > .iconf
	elif [ $v -le 40 ]; then
		echo 9 > .iconf
	elif [ $v -le 45 ]; then
		echo 10 > .iconf
	elif [ $v -le 50 ]; then
		echo 11 > .iconf
	elif [ $v -le 55 ]; then
		echo 12 > .iconf
	elif [ $v -le 60 ]; then
		echo 13 > .iconf
	elif [ $v -le 65 ]; then
		echo 14 > .iconf
	elif [ $v -le 70 ]; then
		echo 15 > .iconf
	elif [ $v -le 75 ]; then
		echo 16 > .iconf
	elif [ $v -le 80 ]; then
		echo 17 > .iconf
	elif [ $v -le 85 ]; then
		echo 18 > .iconf
	elif [ $v -le 90 ]; then
		echo 19 > .iconf
	elif [ $v -le 95 ]; then
		echo 20 > .iconf
	elif [ $v -eq 100 ]; then
		echo 21 > .iconf
	fi
	
	$DSP/strt.sh 5 $easy $ling $hard & exit 1

elif [ "$1" = m ]; then

	cd "$DC_tlt/practice"
	
	[[ -f l_m ]] && echo $(($(cat l_m)+$easy)) > l_m || echo $easy > l_m
	s=$(cat l_m)
	v=$((100*$s/$all))
	if [ $v -le 1 ]; then
		echo 1 > .iconmc
	elif [ $v -le 5 ]; then
		echo 2 > .iconmc
	elif [ $v -le 10 ]; then
		echo 3 > .iconmc
	elif [ $v -le 15 ]; then
		echo 4 > .iconmc
	elif [ $v -le 20 ]; then
		echo 5 > .iconmc
	elif [ $v -le 25 ]; then
		echo 6 > .iconmc
	elif [ $v -le 30 ]; then
		echo 7 > .iconmc
	elif [ $v -le 35 ]; then
		echo 8 > .iconmc
	elif [ $v -le 40 ]; then
		echo 9 > .iconmc
	elif [ $v -le 45 ]; then
		echo 10 > .iconmc
	elif [ $v -le 50 ]; then
		echo 11 > .iconmc
	elif [ $v -le 55 ]; then
		echo 12 > .iconmc
	elif [ $v -le 60 ]; then
		echo 13 > .iconmc
	elif [ $v -le 65 ]; then
		echo 14 > .iconmc
	elif [ $v -le 70 ]; then
		echo 15 > .iconmc
	elif [ $v -le 75 ]; then
		echo 16 > .iconmc
	elif [ $v -le 80 ]; then
		echo 17 > .iconmc
	elif [ $v -le 85 ]; then
		echo 18 > .iconmc
	elif [ $v -le 90 ]; then
		echo 19 > .iconmc
	elif [ $v -le 95 ]; then
		echo 20 > .iconmc
	elif [ $v -eq 100 ]; then
		echo 21 > .iconmc
	fi

	$DSP/strt.sh 6 $easy $ling $hard & exit 1

elif [ "$1" = w ]; then

	cd "$DC_tlt/practice"
	
	[[ -f l_w ]] && echo $(($(cat l_w)+$easy)) > l_w || echo $easy > l_w
	s=$(cat l_w)
	v=$((100*$s/$all))
	if [ $v -le 1 ]; then
		echo 1 > .iconlw
	elif [ $v -le 5 ]; then
		echo 2 > .iconlw
	elif [ $v -le 10 ]; then
		echo 3 > .iconlw
	elif [ $v -le 15 ]; then
		echo 4 > .iconlw
	elif [ $v -le 20 ]; then
		echo 5 > .iconlw
	elif [ $v -le 25 ]; then
		echo 6 > .iconlw
	elif [ $v -le 30 ]; then
		echo 7 > .iconlw
	elif [ $v -le 35 ]; then
		echo 8 > .iconlw
	elif [ $v -le 40 ]; then
		echo 9 > .iconlw
	elif [ $v -le 45 ]; then
		echo 10 > .iconlw
	elif [ $v -le 50 ]; then
		echo 11 > .iconlw
	elif [ $v -le 55 ]; then
		echo 12 > .iconlw
	elif [ $v -le 60 ]; then
		echo 13 > .iconlw
	elif [ $v -le 65 ]; then
		echo 14 > .iconlw
	elif [ $v -le 70 ]; then
		echo 15 > .iconlw
	elif [ $v -le 75 ]; then
		echo 16 > .iconlw
	elif [ $v -le 80 ]; then
		echo 17 > .iconlw
	elif [ $v -le 85 ]; then
		echo 18 > .iconlw
	elif [ $v -le 90 ]; then
		echo 19 > .iconlw
	elif [ $v -le 95 ]; then
		echo 20 > .iconlw
	elif [ $v -eq 100 ]; then
		echo 21 > .iconlw
	fi
	
	$DSP/strt.sh 7 $easy $ling $hard & exit 1

elif [ "$1" = s ]; then

	cd "$DC_tlt/practice"

	[[ -f l_s ]] && echo $(($(cat l_s)+$easy)) > l_s || echo $easy > l_s
	s=$(cat l_s)
	v=$((100*$s/$all))
	if [ $v -le 1 ]; then
		echo 1 > .iconls
	elif [ $v -le 5 ]; then
		echo 2 > .iconls
	elif [ $v -le 10 ]; then
		echo 3 > .iconls
	elif [ $v -le 15 ]; then
		echo 4 > .iconls
	elif [ $v -le 20 ]; then
		echo 5 > .iconls
	elif [ $v -le 25 ]; then
		echo 6 > .iconls
	elif [ $v -le 30 ]; then
		echo 7 > .iconls
	elif [ $v -le 35 ]; then
		echo 8 > .iconls
	elif [ $v -le 40 ]; then
		echo 9 > .iconls
	elif [ $v -le 45 ]; then
		echo 10 > .iconls
	elif [ $v -le 50 ]; then
		echo 11 > .iconls
	elif [ $v -le 55 ]; then
		echo 12 > .iconls
	elif [ $v -le 60 ]; then
		echo 13 > .iconls
	elif [ $v -le 65 ]; then
		echo 14 > .iconls
	elif [ $v -le 70 ]; then
		echo 15 > .iconls
	elif [ $v -le 75 ]; then
		echo 16 > .iconls
	elif [ $v -le 80 ]; then
		echo 17 > .iconls
	elif [ $v -le 85 ]; then
		echo 18 > .iconls
	elif [ $v -le 90 ]; then
		echo 19 > .iconls
	elif [ $v -le 95 ]; then
		echo 20 > .iconls
	elif [ $v -eq 100 ]; then
		echo 21 > .iconls
	fi
	
	$DSP/strt.sh 8 $easy $ling $hard & exit 1
fi
