#!/bin/bash
# -*- ENCODING: UTF-8 -*-

if [ ! -d "$HOME/.idiomind" ]; then
	/usr/share/idiomind/ifs/1u.sh && exit
	if [ ! -d "$HOME/.idiomind" ]; then
		exit 1
	fi
fi

source /usr/share/idiomind/ifs/c.conf
source $DS/ifs/trans/$lgs/items_lists.conf

function sizes() {
	
	wh=$DC_s/cfg.18
	xrandr | grep '*' | awk '{ print $1 }' > $wh
	sed -i 's/x/\n/' $wh
	y=$(sed -n 2p $wh)
	[[ $y -lt 1020 ]] && y=1020
	echo $(($y*58/100)) >> $wh
	echo $(($y*50/100)) >> $wh
	
	echo $(($y*58/100)) >> $wh
	echo $(($y*34/100)) >> $wh
	
	echo $(($y*63/100)) >> $wh
	echo $(($y*46/100)) >> $wh
	echo $(($y*12/100)) >> $wh
	echo $(($y*35/100)) >> $wh
	echo $(($y*11/100)) >> $wh
	echo $(($y*44/100)) >> $wh
	echo $(($y*41/100)) >> $wh
	echo $(($y*38/100)) >> $wh
}

[[ ! -f $DC_s/cfg.18 ]] && sizes

if [ -z "$1" ]; then

	function new_session() {
		
		echo "--new session"
		
		# write in /tmp
		if [[ ! -d $DT ]]; then
			mkdir $DT
		fi
		
		if [ $? -ne 0 ]; then
			killall yad &
			yad --name=idiomind --image=error --button=gtk-ok:1\
			--text=" $write_err\n\n" --image-on-top --sticky  \
			--width=420 --height=150 --borders=5 --title=Idiomind \
			--skip-taskbar --center --window-icon=idiomind & exit 1
		fi
		
		# look for addons
		addons="$(cd $DS/addons; ls -d *)"
		[[ -f $DC_s/cfg.21 ]] && rm $DC_s/cfg.21
		n=1
		while [ $n -le $(echo "$addons" | wc -l ) ]; do
			set=$(echo "$addons" | sed -n "$n"p)
			echo "/usr/share/idiomind/addons/$set/icon.png" >> $DC_s/cfg.21
			echo "$set" >> $DC_s/cfg.21
			let n++
		done

		# screen size
		sizes
		
		# weekly report
		if ([ "$(date +%u)" = 7 ] && \
		[ "$(sed -n 1p $DC/addons/stats/cnf)" = "TRUE" ]); then
			"$DS/addons/weekly report/cnfg.sh" A &
		fi
		
		# news auto-update
		if [ "$(sed -n 1p "$DC/addons/Learning with news/.cnf")" = "TRUE" ]; then
			(sleep 200
			"$DS/addons/Learning with news/strt.sh" A
			) &
		fi
		
		# backup
		if ([ "$(date +%u)" = 6 ] && \
		[ "$(sed -n 1p $DC_s/cfg.12)" = "TRUE" ]); then
			"$DS/addons/User data/cnfg.sh" C &
		fi
		
		# search updates
		$DS/ifs/tls.sh srch &
		
		# update topics status
		[[ ! -f "$DC_tl/.cfg.1" ]] && touch "$DC_tl/.cfg.1"
		n=1
		while [ $n -le "$(cat "$DC_tl/.cfg.1" | head -50 | wc -l )" ]; do
			tp=$(sed -n "$n"p "$DC_tl/.cfg.1")
			stts=$(echo "$(cat "$DC_tl/$tp/cfg.8")")

			if [ "$stts" = 2 ] || [ "$stts" = 7 ]; then
			
				if [ -f "$DC_tl/$tp/cfg.9" ]; then
	
					dts=$(cat "$DC_tl/$tp/cfg.9" | wc -l)
					if [ $dts = 1 ]; then
						dte=$(sed -n 1p "$DC_tl/$tp/cfg.9")
						TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
						RM=$((100*$TM/10))
					elif [ $dts = 2 ]; then
						dte=$(sed -n 2p "$DC_tl/$tp/cfg.9")
						TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
						RM=$((100*$TM/15))
					elif [ $dts = 3 ]; then
						dte=$(sed -n 3p "$DC_tl/$tp/cfg.9")
						TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
						RM=$((100*$TM/30))
					elif [ $dts = 4 ]; then
						dte=$(sed -n 4p "$DC_tl/$tp/cfg.9")
						TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
						RM=$((100*$TM/60))
					fi
					nstll=$(grep -Fxo "$tp" "$DC_tl/.cfg.3")
					if [ -n "$nstll" ]; then
						if [ "$RM" -ge 100 ]; then
							echo "9" > "$DC_tl/$tp/cfg.8"
						fi
						if [ "$RM" -ge 150 ]; then
							echo "10" > "$DC_tl/$tp/cfg.8"
						fi
					else
						if [ "$RM" -ge 100 ]; then
							echo "4" > "$DC_tl/$tp/cfg.8"
						fi
						if [ "$RM" -ge 150 ]; then
							echo "5" > "$DC_tl/$tp/cfg.8"
						fi
					fi
				fi
			fi
			let n++
		done
		echo "$(date +%d)" > $DC_s/cfg.15
		$DS/mngr.sh mkmn &
	}

	yad --width=185 --height=210 --name=idiomind \
	--geometry=175x190-300-$(sed -n 12p $DC_s/cfg.18) \
	--fixed --title="Idiomind" --no-buttons --skip-taskbar \
	--icons --single-click --on-top --borders=0 \
	--read-dir=$DS/default/new --item-width=65 \
	--window-icon=idiomind --class=idiomind &
	[[ -n "$tpc" ]] && echo "$tpc" > $DC_s/cfg.6
	echo "strt.1.strt" >> \
	$DC/addons/stats/.log &
	
	if [[ ! -d $DT ]]; then
		new_session & exit
	fi
	
	[[ -f $DC_s/cfg.15 ]] && d2=$(cat $DC_s/cfg.15)
	if ([ "$(date +%d)" != "$d2" ] || [ ! -f $DC_s/cfg.15 ]); then
		new_session
	fi
fi

if [[ $(echo "$1" | grep -o '.idmnd') ]]; then

	wth=$(sed -n 3p $DC_s/cfg.18)
	eht=$(sed -n 4p $DC_s/cfg.18)
	dte=$(date "+%d %B")
	c=$(echo $(($RANDOM%1000)))
	if [ ! -d $DT ]; then
		mkdir $DT
	fi
	mkdir $DT/idmimp_$c
	(cp -f $DS/default/p1.sh $DT/p1.$c
	cp -f $DS/default/p2.sh $DT/p2.$c
	sed -i 's/X015x/'$c'/g' $DT/*.$c) &
	cp "$1" $DT/import.tmp
	cd $DT
	mv ./import.tmp ./import.tar.gz
	cd ./idmimp_$c
	tar -xzvf ../import.tar.gz
	ls -t -d -N * > $DT/idmimp_$c/ls
	inme=$(sed -n 1p $DT/idmimp_$c/ls)
	echo "$inme"
	tmp="$DT/idmimp_$c/$inme"
	
	source "$tmp/cfg.12"
	[[ $language_target = English ]] && lng=en
	[[ $language_target = French ]] && lng=fr
	[[ $language_target = German ]] && lng=de
	[[ $language_target = Chinese ]] && lng=zh-cn
	[[ $language_target = Italian ]] && lng=it
	[[ $language_target = Japanese ]] && lng=ja
	[[ $language_target = Portuguese ]] && lng=pt
	[[ $language_target = Spanish ]] && lng=es
	[[ $language_target = Vietnamese ]] && lng=vi
	[[ $language_target = Russian ]] && lng=ru
	[[ $level = 1 ]] && level=$beginner
	[[ $level = 2 ]] && level=$intermediate
	[[ $level = 3 ]] && level=$advanced

	if [ -f "$tmp/words/images/img.png" ]; then
	img="$tmp/words/images/img.png"
	s="\n"
	else
	img="$DS/images/trans.png"
	fi
	
	if [ "$inme" != "$name" ]; then
	
		cstn=$(yad --name=idiomind --image=error --button=gtk-ok:1\
		--text=" <b>$file_err</b>\\n" --image-on-top --sticky \
		--width=280 --height=120 --title=Idiomind \
		--skip-taskbar --center --window-icon=idiomind)
		
		[[ -d $DT/idmimp_$c ]] && rm -fr $DT/idmimp_$c
		rm -f $DT/*.$c $DT/import.tar.gz & exit
	else
		cd "$tmp"
		ws=$(cat "cfg.3" | wc -l)
		ss=$(cat "cfg.4" | wc -l)
		itxt="<big><big>$inme</big></big><small>\\n${language_source^} <b>></b> $language_target\\n$nwords $words $nsentences $sentences $nimages $images\n$llevel $level </small>\n"
		dlck="$DT/p1.$c"
		cat "$tmp/cfg.0" | awk '{print $0""}' | \
		yad --list --name=Idiomind --title="Idiomind" \
		--ellipsize=END --print-all --image-on-top \
		--image="$img" --text="$itxt"  --class=Idiomind \
		--scroll --no-headers --dclick-action="$dlck" \
		--width="$wth" --height="$eht" --image-on-top \
		--window-icon=idiomind --column=Items --center \
		--button="$install":0 --button="$close":1
		ret=$?
			
			if [ "$ret" -eq 1 ]; then
				[[ -d $DT/idmimp_$c ]] && rm -fr $DT/idmimp_$c
				rm -f $DT/*.$c $DT/import.tar.gz & exit
			elif [ "$ret" -eq 0 ]; then
				if2=$(cat $DC/topics/$language_target/.cfg.1 | wc -l)
				snm=$(cat $DC/topics/$language_target/.cfg.1 | grep -Fo "$inme" | wc -l)
				
				if [ $if2 -ge 50 ]; then
					yad  --name=idiomind --center \
					--image=info --class=idiomind \
					--text=" \n$topics_max\n\n" \
					--image-on-top --sticky --skip-taskbar \
					--width=420 --height=150 --title=Idiomind \
					--window-icon=idiomind --button=gtk-ok:1
					[[ -d $DT/idmimp_$c ]] && rm -fr $DT/idmimp_$c
					rm -f $DT/*.$c $DT/import.tar.gz & exit
				fi
		
				if [ "$snm" -ge 1 ]; then
					inm="$inme $snm"
					yad  --name=idiomind --image=info --sticky \
					--text=" $name_eq  \\n $name_eq2 <b>$inm    </b>\n" \
					--class=idiomind --center --skip-taskbar \
					--image-on-top --width=420 --height=150 \
					--window-icon=idiomind --title=Idiomind \
					--button=Cancel:1 --button=gtk-ok:0
						ret=$?
					if [ $ret != 0 ]; then
						[[ -d $DT/idmimp_$c ]] && rm -fr $DT/idmimp_$c
						rm -f $DT/*.$c $DT/import.tar.gz & exit
					fi
				else
					inm="$inme"
				fi

				if [ ! -d "$DM_t/$language_target" ]; then
				mkdir "$DM_t/$language_target"
				mkdir "$DM_t/$language_target/.share"
				mkdir "$DC/topics/$language_target"
				mkdir "$DC_a/Learning with news/$language_target"
				mkdir "$DC_a/Learning with news/$language_target/subscripts"
				"$DS/addons/Learning with news/examples/$language_target"
				cp -f "$DS/addons/Learning with news/examples/$language_target" \
				"$DC_a/Learning with news/$language_target/subscripts/Example"
				fi
				mkdir "$DM/topics/$language_target/$inm"
				mkdir "$DC/topics/$language_target/$inm"
				drit="$DM/topics/$language_target/$inm"
				dric="$DC/topics/$language_target/$inm"
				mkdir "$dric/practice"
				cp -f $DS/practice/default/.* \
				"$dric/practice"
				cd "$tmp"
				cp -n ./.audio/*.mp3 "$DM_t/$language_target/.share/"
				[[ -d ./.audio ]] && rm -fr ./.audio
				cp -fr ./.* "$drit/"
				cp -f cfg.12 "$dric/cfg.12"
				echo "6" > "$dric/cfg.8"
				cp -f cfg.0 "$dric/cfg.0"
				cp -f cfg.0 "$dric/.cfg.11"
				cp -f cfg.0 "$dric/cfg.1"
				cp -f cfg.3 "$dric/cfg.3"
				cp -f cfg.4 "$dric/cfg.4"
				cp -f cfg.5 "$dric/cfg.5"
				cp -f cfg.10 "$dric/cfg.10"
				cp -f $DS/default/tpc.sh "$dric/tpc.sh"
				chmod +x "$dric/tpc.sh"
				echo "$lng" > $DC_s/cfg.10
				echo "$language_target" >> $DC_s/cfg.10
				cd "$dric"
				echo $dte > cfg.13
				echo "$inm" >> "$DC/topics/$language_target/.cfg.3"
				sed -i 's/'"$inm"'//g' "$DC/topics/$language_target/.cfg.2"
				sed '/^$/d' $DC/topics/$language_target/.cfg.2 > $DC/topics/$language_target/.cfg.2_
				mv -f $DC/topics/$language_target/.cfg.2_ $DC/topics/$language_target/.cfg.2
				$DS/mngr.sh mkmn &&
				"$dric/tpc.sh" &
				[[ -d $DT/idmimp_$c ]] && rm -fr $DT/idmimp_$c
				rm -f $DT/*.$c $DT/import.tar.gz & exit
			else
				[[ -d $DT/idmimp_$c ]] && rm -fr $DT/idmimp_$c
				rm -f $DT/*.$c $DT/import.tar.gz & exit
			fi
	exit 0
	fi
	
# topic
elif [[ $1 = topic ]]; then

	wth=$(sed -n 3p $DC_s/cfg.18)
	eht=$(sed -n 4p $DC_s/cfg.18)
	mde=$(sed -n 2p $DC_s/cfg.8)

	if ([ -n "$tpc" ] || [ $(echo "$mde" | grep "fd") ]); then
	
		if [ -n "$tpc" ]; then
			[[ ! -f "$DC_tlt/cfg.0" ]] && touch "$DC_tlt/cfg.0"
			[[ ! -f "$DC_tlt/cfg.1" ]] && touch "$DC_tlt/cfg.1"
			[[ ! -f "$DC_tlt/cfg.2" ]] && touch "$DC_tlt/cfg.2"
			[[ ! -f "$DC_tlt/cfg.10" ]] && touch "$DC_tlt/cfg.10"
			
			ls0="$DC_tlt/cfg.0"
			ls1="$DC_tlt/cfg.1"
			ls2="$DC_tlt/cfg.2"
			nt="$DC_tlt/cfg.10"
			cd "$DC_tlt"
			ws=$(cat cfg.3 | wc -l)
			ss=$(cat cfg.4 | wc -l)
			c=$(echo $(($RANDOM%100000)))
			KEY=$c
			cnf1=$(mktemp $DT/cnf1.XXX.x)
			cnf3=$(mktemp $DT/cnf3.XXX.x)
			cd $DS

			if [ -f "$DM_tlt/words/images/img.png" ]; then
			img="$DM_tlt/words/images/img.png"
			else
			img=$DS/images/trans.png
			fi
			echo "tpcs.$tpc.tpcs" >> \
			$DC/addons/stats/.log &
			inx=$(cat "$ls0" | wc -l)
			tb1=$(cat "$ls1" | wc -l)
			tb2=$(cat "$ls2" | wc -l)
		fi
	else
		if [ "$(cat $DC_tl/.cfg.1 | wc -l)" -ge 1 ]; then
			exit
		else
			yad --window-icon=idiomind --name=idiomind \
			--image=idiomind --on-top --skip-taskbar \
			--text="$there_are_no_topics ($lgtl)\n" \
			--image-on-top --center --sticky \
			--width=420 --height=150 --borders=5 \
			--skip-taskbar --title="$nothing" \
			--button="  Ok  ":0 & exit
		fi
	fi

	# own
	if echo "$mde" | grep "wn"; then
	
		[ -z "$tpc" ] && exit 1

		itxt="<big><big>$tpc </big></big><small>\\n$ss $sentences $ws $words\n</small>\n"
		itxt2="<span color='#ABABAB'><small> $created_by $author $on ${category^}  $date_u</small></span>"

		if [ "$inx" -lt 1 ]; then
			
			yad --text-info --plug=$KEY --margins=14 \
			--tabnum=1 --fore='gray40' --wrap --filename="$nt" \
			--show-uri --fontname=vendana --editable > "$cnf3" &
			yad --notebook --name=Idiomind --center \
			--class=Idiomind --align=right --key=$KEY \
			--window-icon=$DS/images/idiomind.png \
			--tab-borders=0 --center --title="Idiomind" \
			--image="$img" --text="$itxt" --tab=" $notes " \
			--ellipsize=END --image-on-top --always-print-result \
			--width="$wth" --height="$eht" --borders=0 \
			--button="Play":$DS/play.sh \
			--button="$delete":"$DS/mngr.sh dlt"
					
				if [ -f $cnf3 ]; then
					if [ "$(cat $cnf3)" != "$(cat "$nt")" ]; then
						mv -f $cnf3 "$nt"
					fi
				fi
			rm -f $DT/*.x
			
		elif [ "$tb1" -ge 1 ]; then
		
			if [ -f "$DC_tlt/cfg.9" ] && [ -f "$DC_tlt/cfg.7" ]; then
			
				dts=$(cat "$DC_tlt/cfg.9" | wc -l)
				if [ $dts = 1 ]; then
					dte=$(sed -n 1p "$DC_tlt/cfg.9")
					adv="<b>  10 $cuestion_review </b>"
					TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
					RM=$((100*$TM/10))
					tdays=10
				elif [ $dts = 2 ]; then
					dte=$(sed -n 2p "$DC_tlt/cfg.9")
					adv="<b>  15 $cuestion_review </b>"
					TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
					RM=$((100*$TM/15))
					tdays=15
				elif [ $dts = 3 ]; then
					dte=$(sed -n 3p "$DC_tlt/cfg.9")
					adv="<b>  30 $cuestion_review </b>"
					TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
					RM=$((100*$TM/30))
					tdays=30
				elif [ $dts = 4 ]; then
					dte=$(sed -n 4p "$DC_tlt/cfg.9")
					adv="<b>  60 $cuestion_review </b>"
					TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
					RM=$((100*$TM/60))
					tdays=60
				fi

				if [ "$RM" -ge 100 ]; then
					echo "4" > "$DC_tlt/cfg.8"
					$DS/mngr.sh mkmn &
					RM=100
					yad --title="$tpc" --window-icon=idiomind \
					--borders=20 --buttons-layout=edge \
					--image=dialog-question --on-top --center \
					--window-icon=$DS/images/idiomind.png \
					--buttons-layout=edge --class=idiomind \
					--button="       $notyet       ":1 \
					--button="        $review        ":2 \
					--text="$adv" --name=idiomind \
					--width=420 --height=150
					ret=$?
						if [ "$ret" -eq 2 ]; then
							echo "3" > "$DC_tlt/cfg.8"
							$DS/mngr.sh mkmn
							rm -f "$ls2" 
							rm -f "$DC_tlt/cfg.7"
							cp -f "$ls0" "$ls1" && idiomind topic & exit 1
						fi 
				fi
				yad --align=center --borders=80 \
				--text="<u><b>$learned</b></u>   * $new_items ($tb1).\\n$time_review: $tdays" \
				--bar="":NORM $RM \
				--multi-progress --plug=$KEY --tabnum=1 &
				cat "$ls2" | yad \
				--no-headers --list --plug=$KEY --tabnum=2 \
				--expand-column=1 --ellipsize=END --print-all \
				--column=Name:TEXT --column=Review:CHK \
				--dclick-action='./vwr.sh v2' &
				yad --text-info --plug=$KEY --margins=14 \
				--wrap --text="$itxt2" --editable --tabnum=3 --fore='gray40' \
				--show-uri --fontname=vendana --filename="$nt" > "$cnf3" &
				yad --notebook --name=Idiomind --center \
				--class=Idiomind --align=right --key=$KEY \
				--tab-borders=0 --center --title="Idiomind" \
				--image="$img" --text="$itxt" \
				--window-icon=$DS/images/idiomind.png \
				--tab=" $review " \
				--tab=" $learned ($tb2) " \
				--tab=" $notes " \
				--ellipsize=END --image-on-top --always-print-result \
				--width="$wth" --height="$eht" --borders=0 \
				--button="$review":4 --button="$edit":3 >/dev/null 2>&1
			else
				cat "$ls1" | awk '{print $0"\n"}' | yad \
				--no-headers --list --plug=$KEY --tabnum=1 \
				--dclick-action='./vwr.sh v1' --print-all \
				--expand-column=1 --ellipsize=END \
				--column=Name:TEXT --column=Learned:CHK > "$cnf1" &
				cat "$ls2" | yad \
				--no-headers --list --plug=$KEY --tabnum=2 \
				--expand-column=0 --ellipsize=END --print-all \
				--column=Name:TEXT  \
				--dclick-action='./vwr.sh v2' &
				yad --text-info --plug=$KEY --margins=14 \
				--tabnum=3 --text="$itxt2" --fore='gray40' --wrap --editable \
				--show-uri --fontname=vendana \
				--filename="$nt" > "$cnf3" &
				yad --notebook --name=Idiomind --center --key=$KEY \
				--class=Idiomind --align=right \
				--window-icon=$DS/images/idiomind.png \
				--tab-borders=0 --center --title="Idiomind" \
				--image="$img" --text="$itxt" \
				--tab="  $learning ($tb1) " \
				--tab="  $learned ($tb2) " \
				--tab=" $notes " \
				--ellipsize=END --image-on-top --always-print-result \
				--width="$wth" --height="$eht" --borders=0 \
				--button="Play":$DS/play.sh --button="$practice":5 \
				--button="$edit":3
				
			fi
				ret=$?
				
				if [ $ret -eq 3 ]; then
					./mngr.sh edit &
					
				elif [ $ret -eq 5 ]; then
					rm -f $DT/*.x
					$DS/practice/strt.sh &
					
				elif [ $ret -eq 4 ]; then
					yad --title="$tpc" --window-icon=idiomind \
					--borders=5 --name=idiomind \
					--image=dialog-question \
					--on-top --window-icon=idiomind \
					--center --class=idiomind \
					--button="$onlynews":3 \
					--button="$all":2 \
					--text="  $cuestion_review2" \
					--width=420 --height=150
						ret=$? 
						if [ "$ret" -eq 2 ]; then
							rm -f "$DC_tlt/cfg.7"
							rm -f $DT/*.x
							echo "3" > "$DC_tlt/cfg.8"
							$DS/mngr.sh mkmn
							rm -f "$ls2"
							cp -f "$ls0" "$ls1" && idiomind topic & exit 1
							
						elif [ "$ret" -eq 3 ]; then
							rm -f $DT/*.x
							rm -f "$DC_tlt/cfg.7" && idiomind topic & exit 1
						fi
					
				else
				
					if [ -f $cnf3 ]; then
						if [ "$(cat $cnf3)" != "$(cat "$nt")" ]; then
							mv -f $cnf3 "$nt"
						fi
					fi
					
					if [ -n "$(cat "$cnf1" | grep -o TRUE)" ]; then
						grep -Rl "|FALSE|" "$cnf1" | while read tab1 ; do
							 sed '/|FALSE|/d' "$cnf1" > tmpf1
							 mv tmpf1 $tab1
						done
						
						sed -i 's/|TRUE|//g' "$cnf1"
						cat "$cnf1" >> "$ls2"

						cnt=$(cat "$cnf1" | wc -l)
						grep -F -x -v -f "$cnf1" "$ls1" > $DT/ls1.x
						mv -f $DT/ls1.x "$ls1"
						if [ -n "$(cat "$ls1" | sort -n | uniq -dc)" ]; then
							cat "$ls1" | awk '!array_temp[$0]++' > $DT/ls1.x
							sed '/^$/d' $DT/ls1.x > "$ls1"
						fi
						echo "okim.$cnt.okim" >> \
						$DC/addons/stats/.log &	
					fi
					
					rm -f $DT/*.x
				fi
			
		elif [ "$tb1" -eq 0 ]; then
		
			if [ ! -f "$DC_tlt/cfg.7" ]; then
				> "$DC_tlt/cfg.7"
				echo "$(date +%m/%d/%Y)" > "$DC_tlt/cfg.9"
				echo "2" > "$DC_tlt/cfg.8"
				$DS/mngr.sh mkmn &
			fi
			dts=$(cat "$DC_tlt/cfg.9" | wc -l)
			if [ $dts = 1 ]; then
				dte=$(sed -n 1p "$DC_tlt/cfg.9")
				adv="<b>  10 $cuestion_review </b>"
				TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
				RM=$((100*$TM/10))
				tdays=10
			elif [ $dts = 2 ]; then
				dte=$(sed -n 2p "$DC_tlt/cfg.9")
				adv="<b>  15 $cuestion_review </b>"
				TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
				RM=$((100*$TM/15))
				tdays=15
			elif [ $dts = 3 ]; then
				dte=$(sed -n 3p "$DC_tlt/cfg.9")
				adv="<b>  30 $cuestion_review </b>"
				TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
				RM=$((100*$TM/30))
				tdays=30
			elif [ $dts = 4 ]; then
				dte=$(sed -n 4p "$DC_tlt/cfg.9")
				adv="<b>  60 $cuestion_review </b>"
				TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
				RM=$((100*$TM/60))
				tdays=60
			fi
				
			if [ "$RM" -ge 100 ]; then
				echo "4" > "$DC_tlt/cfg.8"
				$DS/mngr.sh mkmn &
				RM=100
				yad --title="$tpc" \
				--borders=20 --buttons-layout=edge --name=idiomind \
				--image=dialog-question --on-top --center \
				--window-icon=$DS/images/idiomind.png \
				--buttons-layout=edge --class=idiomind \
				--button="       $notyet       ":1 \
				--button="        $review        ":2 \
				--text="$adv" --width=420 --height=150
				ret=$? 
					if [ "$ret" -eq 2 ]; then
						rm -f "$DC_tlt/cfg.7"
						rm -f $DT/*.x
						echo "3" > "$DC_tlt/cfg.8"
						$DS/mngr.sh mkmn
						rm -f "$ls2" 
						cp -f "$ls0" "$ls1" && idiomind topic & exit 1
					fi 
			fi

			yad --align=center --borders=80 \
			--text="<u><b>$learned</b></u>\\n$time_review ($tdays $days)" \
			--bar="":NORM $RM \
			--multi-progress --plug=$KEY --tabnum=1 &
			cat "$ls2" | yad \
			--no-headers --list --plug=$KEY --tabnum=2 \
			--expand-column=1 --ellipsize=END --print-all \
			--column=Name:TEXT --column=Review:CHK \
			--dclick-action='./vwr.sh v2' &
			yad --text-info --plug=$KEY --margins=14 --text="$itxt2" \
			--tabnum=3 --fore='gray40' --wrap --filename="$nt" \
			--show-uri --fontname=vendana --editable > "$cnf3" &
			yad --notebook --name=Idiomind --center \
			--class=Idiomind --align=right --key=$KEY \
			--tab-borders=0 --center --title="Idiomind" \
			--image="$img" --text="$itxt" \
			--window-icon=$DS/images/idiomind.png \
			--tab=" $review " \
			--tab=" $learned ($tb2) " \
			--tab=" $notes " \
			--ellipsize=END --image-on-top --always-print-result \
			--width="$wth" --height="$eht" --borders=0 \
			--button="$edit":3
				ret=$?
				
				if [ $ret -eq 3 ]; then
					./mngr.sh edit &
					
				elif [ $ret -eq 5 ]; then
					$DS/practice/strt.sh &
				
				else
					if [ -f $cnf3 ]; then
						if [ "$(cat $cnf3)" != "$(cat "$nt")" ]; then
							mv -f $cnf3 "$nt"
						fi
					fi
					if [ -n "$(cat "$cnf1" | grep -o TRUE)" ]; then
						grep -Rl "|FALSE|" "$cnf1" | while read tab1 ; do
							 sed '/|FALSE|/d' "$cnf1" > tmpf1
							 mv tmpf1 $tab1
						done
						sed -i 's/|TRUE|//g' "$cnf1"
						cat "$cnf1" >> "$ls2"
						cnt=$(cat "$cnf1" | wc -l)
						grep -F -x -v -f "$cnf1" "$ls1" > $DT/ls1.x
						mv -f $DT/ls1.x "$ls1"
						if [ -n "$(cat "$ls1" | sort -n | uniq -dc)" ]; then
							cat "$ls1" | awk '!array_temp[$0]++' > $DT/ls1.x
							sed '/^$/d' $DT/ls1.x > "$ls1"
						fi
						echo "okim.$cnt.okim" >> \
						$DC/addons/stats/.log &
					fi
				fi
			rm -f $DT/*.x
		fi	
	# nstll
	elif echo "$mde" | grep "istll"; then
	
		[ -z "$tpc" ] && exit 1
		
		source "$DC_tlt/cfg.12"
		itxt="<big><big>$tpc </big></big><small>\\n$ss $sentences $ws $words\n</small>\n"
		itxt2="<small> $created_by $author $on <span color='#6E9FD4'>${category^}</span>  $date_u</small>"
		
		if [ "$tb1" -ge 1 ]; then
		
			if [ -f "$DC_tlt/cfg.9" ] && [ -f "$DC_tlt/cfg.7" ]; then
			
				dts=$(cat "$DC_tlt/cfg.9" | wc -l)
				if [ $dts = 1 ]; then
					dte=$(sed -n 1p "$DC_tlt/cfg.9")
					adv="<b>   10 $cuestion_review </b>"
					TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
					RM=$((100*$TM/10))
					tdays=10
				elif [ $dts = 2 ]; then
					dte=$(sed -n 2p "$DC_tlt/cfg.9")
					adv="<b> 15 $cuestion_review </b>"
					TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
					RM=$((100*$TM/15))
					tdays=15
				elif [ $dts = 3 ]; then
					dte=$(sed -n 3p "$DC_tlt/cfg.9")
					adv="<b>  30 $cuestion_review </b>"
					TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
					RM=$((100*$TM/30))
					tdays=30
				elif [ $dts = 4 ]; then
					dte=$(sed -n 4p "$DC_tlt/cfg.9")
					adv="<b>  60 $cuestion_review </b>"
					TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
					RM=$((100*$TM/60))
					tdays=60
				fi
			
				if [ "$RM" -ge 100 ]; then
					echo "4" > "$DC_tlt/cfg.8"
					$DS/mngr.sh mkmn &
					RM=100
					yad --title="$tpc" \
					--window-icon=$DS/images/idiomind.png \
					--borders=20 --buttons-layout=edge --name=idiomind \
					--image=dialog-question --on-top \
					--buttons-layout=edge --center --class=idiomind \
					--button="       $notyet       ":1 \
					--button="        $review        ":2 \
					--text="$adv" \
					--width=420 --height=150
					ret=$?
						if [ "$ret" -eq 2 ]; then
							rm -f "$DC_tlt/cfg.7"
							rm -f $DT/*.x
							echo "3" > "$DC_tlt/cfg.8"
							$DS/mngr.sh mkmn
							rm -f "$ls2"
							cp -f "$ls0" "$ls1" && idiomind topic & exit 1
						fi 
					fi

				yad --align=center --borders=80 \
				--text="<u><b>$learned</b></u>\\n   * $new_items ($tb1).\\n$time_review: $tdays" \
				--bar="":NORM $RM \
				--multi-progress --plug=$KEY --tabnum=1 &
				cat "$ls2" | yad \
				--no-headers --list --plug=$KEY --tabnum=2 \
				--expand-column=1 --ellipsize=END --print-all \
				--column=Name:TEXT --column=Review:CHK \
				--dclick-action='./vwr.sh v2' &
				yad --text-info --plug=$KEY --margins=14 \
				--text="$itxt2" \
				--tabnum=3 --fore='gray40' --wrap --filename="$nt" \
				--show-uri --fontname=vendana --editable > "$cnf3" &
				yad --notebook --name=Idiomind --center \
				--class=Idiomind --align=right --key=$KEY \
				--tab-borders=0 --center --title="Idiomind" \
				--image="$img" --text="$itxt" \
				--window-icon=$DS/images/idiomind.png \
				--tab=" $review " \
				--tab=" $learned ($tb2) " \
				--tab=" $notes " \
				--ellipsize=END --image-on-top --always-print-result \
				--width="$wth" --height="$eht" --borders=0  \
				--button="$review":4 --button="$edit":3
			else
				cat "$ls1" | awk '{print $0"\n"}' | yad \
				--no-headers --list --plug=$KEY --tabnum=1 $t \
				--expand-column=1 --ellipsize=END --print-all \
				--column=Name:TEXT --column=Learned:CHK \
				--dclick-action='./vwr.sh v1' > "$cnf1" &
				cat "$ls2" | yad \
				--no-headers --list --plug=$KEY --tabnum=2 \
				--expand-column=1 --ellipsize=END --print-all \
				--column=Name:TEXT --column=Review:CHK \
				--dclick-action='./vwr.sh v2' &
				yad --text-info --plug=$KEY --margins=14 \
				--text="$itxt2" \
				--tabnum=3 --fore='gray40' --wrap --filename="$nt" \
				--show-uri --fontname=vendana --editable > "$cnf3" &
				yad --notebook --name=Idiomind --center  \
				--class=Idiomind --align=right --key=$KEY \
				--tab-borders=0 --center --title="Idiomind" \
				--image="$img" --text="$itxt" --always-print-result \
				--tab=" $learning ($tb1) " \
				--tab=" $learned ($tb2) " \
				--tab=" $notes " \
				--ellipsize=END --image-on-top \
				--window-icon=$DS/images/idiomind.png \
				--width="$wth" --height="$eht" --borders=0 \
				--button="Play":$DS/play.sh --button="$practice":5 \
				--button="$edit":3
			fi
				ret=$?
				
				if [ $ret -eq 3 ]; then
					./mngr.sh edit &
				
				elif [ $ret -eq 5 ]; then
					rm -f $DT/*.x
					$DS/practice/strt.sh &
					
				elif [ $ret -eq 4 ]; then
					yad --title="$tpc" --window-icon=idiomind \
					--borders=5 --name=idiomind \
					--image=dialog-question \
					--on-top --window-icon=idiomind \
					--center --class=idiomind \
					--button="$onlynews":3 \
					--button="$all":2 \
					--text="  $cuestion_review2 " \
					--width=420 --height=150
						ret=$? 
						if [ "$ret" -eq 2 ]; then
							rm -f "$DC_tlt/cfg.7"
							rm -f $DT/*.x
							echo "8" > "$DC_tlt/cfg.8"
							$DS/mngr.sh mkmn
							rm -f "$ls2"
							cp -f "$ls0" "$ls1" && idiomind topic & exit 1
							
						elif [ "$ret" -eq 3 ]; then
							rm -f $DT/*.x
							rm -f "$DC_tlt/cfg.7" && idiomind topic & exit 1
						fi
				
				else
					if [ -f $cnf3 ]; then
						if [ "$(cat $cnf3)" != "$(cat "$nt")" ]; then
							mv -f $cnf3 "$nt"
						fi
					fi
					if [ -n "$(cat "$cnf1" | grep -o TRUE)" ]; then
						grep -Rl "|FALSE|" "$cnf1" | while read tab1 ; do
							 sed '/|FALSE|/d' "$cnf1" > tmpf1
							 mv tmpf1 $tab1
						done
						sed -i 's/|TRUE|//g' "$cnf1"
						cat "$cnf1" >> "$ls2"
						cnt=$(cat "$cnf1" | wc -l)
						grep -F -x -v -f "$cnf1" "$ls1" > $DT/ls1.x
						mv -f $DT/ls1.x "$ls1"
						if [ -n "$(cat "$ls1" | sort -n | uniq -dc)" ]; then
							cat "$ls1" | awk '!array_temp[$0]++' > $DT/ls1.x
							sed '/^$/d' $DT/ls1.x > "$ls1"
						fi
						echo "okim.$cnt.okim" >> \
						$DC/addons/stats/.log &
					fi
				rm -f $DT/*.x
				fi
		
		elif [ "$tb1" -eq 0 ]; then
		
			if [ ! -f "$DC_tlt/cfg.7" ]; then
				> "$DC_tlt/cfg.7"
				echo "$(date +%m/%d/%Y)" > "$DC_tlt/cfg.9"
				echo "7" > "$DC_tlt/cfg.8"
				$DS/mngr.sh mkmn &
			fi
			dts=$(cat "$DC_tlt/cfg.9" | wc -l)
			if [ $dts = 1 ]; then
				dte=$(sed -n 1p "$DC_tlt/cfg.9")
				adv="<b>  10 $cuestion_review </b>"
				TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
				RM=$((100*$TM/10))
				tdays=10
			elif [ $dts = 2 ]; then
				dte=$(sed -n 2p "$DC_tlt/cfg.9")
				adv="<b>  15 $cuestion_review </b>"
				TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
				RM=$((100*$TM/15))
				tdays=15
			elif [ $dts = 3 ]; then
				dte=$(sed -n 3p "$DC_tlt/cfg.9")
				adv="<b>  30 $cuestion_review </b>"
				TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
				RM=$((100*$TM/30))
				tdays=30
			elif [ $dts = 4 ]; then
				dte=$(sed -n 4p "$DC_tlt/cfg.9")
				adv="<b>  60 $cuestion_review </b>"
				TM=$(echo $(( ( $(date +%s) - $(date -d "$dte" +%s) ) /(24 * 60 * 60 ) )))
				RM=$((100*$TM/60))
				tdays=60
			fi
			
			if [ "$RM" -ge 100 ]; then
				echo "9" > "$DC_tlt/cfg.8"
				$DS/mngr.sh mkmn &
				RM=100
				
				yad --title="$tpc" \
				--borders=20 --buttons-layout=edge --class=idiomind \
				--image=dialog-question \
				--window-icon=$DS/images/idiomind.png \
				--on-top \
				--buttons-layout=edge --center --name=idiomind \
				--button="       $notyet       ":1 \
				--button="        $review        ":2 \
				--text="$adv" \
				--width=420 --height=150
					ret=$?
					
					if [ "$ret" -eq 2 ]; then
						echo "8" > "$DC_tlt/cfg.8"
						rm -f "$DC_tlt/cfg.7"
						rm -f $DT/*.x
						$DS/mngr.sh mkmn &
						rm -f "$ls2"
						cp -f "$ls0" "$ls1" && idiomind topic & exit 1
					fi
			fi
			
			yad --align=center --borders=80 \
			--text="<u><b>$learned</b></u>\\n$time_review ($tdays $days)" \
			--bar="":NORM $RM \
			--multi-progress --plug=$KEY --tabnum=1 &
			cat "$ls2" | yad \
			--no-headers --list --plug=$KEY --tabnum=2 \
			--expand-column=1 --ellipsize=END --print-all \
			--column=Name:TEXT --column=Review:CHK \
			--dclick-action='./vwr.sh v2' &
			yad --text-info --plug=$KEY --margins=14 \
			--text="$itxt2" \
			--tabnum=3 --fore='gray40' --wrap --filename="$nt" \
			--show-uri --fontname=vendana --editable > "$cnf3" &
			yad --notebook --name=Idiomind --center  \
			--class=Idiomind --align=right --key=$KEY \
			--tab-borders=0 --center --title="Idiomind" \
			--image="$img" --text="$itxt" \
			--window-icon=$DS/images/idiomind.png \
			--tab=" $review " \
			--tab=" $learned ($tb2) " \
			--tab=" $notes " \
			--ellipsize=END --image-on-top --always-print-result \
			--width="$wth" --height="$eht" --borders=0 \
			--button="$edit":3
				ret=$?
				
				if [ $ret -eq 3 ]; then
					./mngr.sh edit &
				
				elif [ $ret -eq 5 ]; then
					rm -f $DT/*.x
					$DS/practice/strt.sh &
				
				else
					if [ -f $cnf3 ]; then
						if [ "$(cat $cnf3)" != "$(cat "$nt")" ]; then
							mv -f $cnf3 "$nt"
						fi
					fi
					if [ -n "$(cat "$cnf1" | grep -o TRUE)" ]; then
						grep -Rl "|FALSE|" "$cnf1" | while read tab1 ; do
							 sed '/|FALSE|/d' "$cnf1" > tmpf1
							 mv tmpf1 $tab1
						done
						sed -i 's/|TRUE|//g' "$cnf1"
						cat "$cnf1" >> "$ls2"
						cnt=$(cat "$cnf1" | wc -l)
						grep -F -x -v -f "$cnf1" "$ls1" > $DT/ls1.x
						mv -f $DT/ls1.x "$ls1"
						if [ -n "$(cat "$ls1" | sort -n | uniq -dc)" ]; then
							cat "$ls1" | awk '!array_temp[$0]++' > $DT/ls1.x
							sed '/^$/d' $DT/ls1.x > "$ls1"
						fi
						
						cho "okim.$cnt.okim" >> \
						$DC/addons/stats/.log &
					fi
					
				fi
			fi
			rm -f $DT/*.x & exit
	#feeds
	elif echo "$mde" | grep "fd"; then
		dir1="$DM_tl/Feeds"
		dir2="$DC/addons/Learning with news"
		DF="$DS/addons/Learning with news"
		FEED=$(cat "$dir2/$lgtl/.rss")
		ICON="$DF/images/rss.png"
		c=$(echo $(($RANDOM%100000)))
		STT="$(cat $DT/.uptf)"
		
		KEY=$c
		if echo "$STT" | grep "updating..."; then
			info=$(echo "<i>"$updating"...</i>")
			FEED=$(cat "$DT/.rss")
		else
			info=$(cat $DC_tl/Feeds/.dt)
		fi
		if [[ ! -f "$DC_tl/Feeds/cfg.1" ]]; then
		cd "$dir1/conten"
		ls -t *.mp3 > "$DC_tl/Feeds/cfg.1"
		sed -i 's/.mp3//g' "$DC_tl/Feeds/cfg.1"
		fi
		cd "$DF"
		cat "$DC_tl/Feeds/cfg.1" | yad \
		--no-headers --list --listen --plug=$KEY --tabnum=1 \
		--text=" <small>$info</small>" \
		--expand-column=1 --ellipsize=END --print-all \
		--column=Name:TEXT --dclick-action='./vwr.sh V1' &
		cat "$DC_tl/Feeds/cfg.0" | awk '{print $0""}' \
		| yad --no-headers --list --listen --plug=$KEY --tabnum=2 \
		--expand-column=1 --ellipsize=END --print-all \
		--column=Name:TEXT --dclick-action='./vwr.sh V2' &
		yad --notebook --name=Idiomind --center \
		--class=Idiomind --align=right --key=$KEY \
		--text=" <big><big>$title_rss </big></big>\\n <small>$FEED</small>\n\n" \
		--image="$ICON" --image-on-top  \
		--tab-borders=0 --center --title="$FEED" \
		--tab="  $news  " \
		--tab=" $saved_conten " \
		--ellipsize=END --image-on-top \
		--window-icon=$DS/images/idiomind.png \
		--width="$wth" --height="$eht" --borders=0 \
		--button="Play":$DS/play.sh \
		--button="$update":2 \
		--button="$edit":3
			ret=$?
			
			if [ $ret -eq 0 ]; then
				rm -f $DT/*.x
				"$DF/cnfg.sh" & killall topic.sh & exit 1
			
			elif [ $ret -eq 3 ]; then
				rm -f $DT/*.x
				"$DF/cnfg.sh" edit & exit 1
			
			elif [ $ret -eq 2 ]; then
				rm -f $DT/*.x
				"$DF/strt.sh" & exit 1
			fi
			
	elif echo "$mde" | grep "wr"; then
		"$DS/addons/weekly report/cnfg.sh" T & exit 1
	fi
	
	rm -f $DT/*.x
	
elif [[ "$1" = "--version" ]]; then
	echo "2.2-beta" & exit
elif [[ "$1" = "-v" ]]; then
	echo "2.2-beta" & exit
fi
