#!/bin/bash
source /usr/share/idiomind/ifs/c.conf

if [ $1 = nt ]; then
	if [ ! -f "$nt".odt ] || [ -z "$(cat $DC_s/nt)" ]; then
	
		sv=$($yad --save --center --borders=10 --on-top \
		--window-icon=idiomind --skip-taskbar --title=Notes \
		--file --width=600 --height=500 --button=gtk-ok:0)
		echo "$sv" > $DC_s/nt
		cp -f $DS/default/notes.odt "$sv".odt
		nt="$(cat $DC_s/nt)"
		
		[[ -z "$nt" ]] && exit 1
		xdg-open "$nt".odt
		exit
	else
		nt="$(cat $DC_s/nt)"
		xdg-open "$nt".odt
		exit
	fi
		
elif [ $1 = rpsg ]; then
	xdg-open https://www.idiomind.com.ar/contact.html
	exit

elif [ $1 = how ]; then
	xdg-open https://www.idiomind.com.ar/manual.html
	exit

elif [ $1 = mkdnt ]; then
	xdg-open https://www.idiomind.com.ar/makedonate.html
	exit

elif [ $1 = web ]; then
	lng=$(echo "$lgt" | awk '{print tolower($0)}')
	xdg-open http://$lgsl.idiomind.com.ar/$lng
	exit

elif [ $1 = isrc ]; then
	lng=$(echo "$lgsl" | awk '{print tolower($0)}')
	xdg-open http://$lgt.idiomind.com.ar/$lng
	exit

elif [ $1 = updt ]; then
	cd $DT/
	wget http://www.idiomind.com.ar/data/info_u.sh
	chmod +x $DT/info_u.sh
	$DT/info_u.sh
	sleep 40
	rm -R $DT/info_u.sh
	exit

elif [ $1 = srch ]; then
	if [ ! -f $DC_s/updt ]; then
		echo `date +%d` > $DC_s/updt
	fi

	d1=$(cat $DC_s/updt)
	d2=`date +%d`

	if [ $(cat $DC_s/updt) = 28 ]; then
		rm -f $DC_s/updt_l
	fi

	[ -f $DC_s/updt_l ] && exit 1

	if [ $(cat $DC_s/updt) -ne $(date +%d) ]; then
		sleep 1
	
	echo "$d2" > $HOME/.config/idiomind/s/updt
	wget -O/dev/null -q http://tmp.site50.net/uploads/recents/19Q.Adverbs%20of%20frequency.idmnd && yad --text="<b>  Esta disponible una nueva version  </b>" \
	--image=info --title="Idiomind 1.5.0" --window-icon=idiomind \
	--on-top --skip-taskbar --sticky \
	--center --name=idiomind --borders=15 \
	--button="Cancel":1 \
	--button="Recordarmelo después":2 \
	--button="   Download   ":0 \
	--width=400 --height=150
	ret=$?
	if [ "$ret" -eq 0 ]; then
		xdg-open http://www.idiomind.com.ar/downloads.html & exit
	elif [ "$ret" -eq 2 ]; then
		echo `date +%d` > $HOME/.config/idiomind/s/updt & exit
	elif [ "$ret" -eq 1 ]; then
		echo `date +%d` > $HOME/.config/idiomind/s/updt_l & exit
	fi  || exit 1
fi

elif [ $1 = pdf ]; then
	cd $HOME &&

	pdf=$($yad --save --center --borders=10 \
	--on-top --filename="$HOME/$tpc.pdf" \
	--window-icon=idiomind --skip-taskbar --title="Export " \
	--file --width=600 --height=500 --button=gtk-ok:0 )
	ret=$?
z
	if [[ "$ret" -eq 0 ]]; then
		
		dte=$(date "+%d %B %Y")
		mkdir $DT/mkhtml
		mkdir $DT/mkhtml/images
		nts=$(cat -e "$DC_tlt/nt" | sed 's/\$/<br>/g')
		cd $DT/mkhtml
		cp -f "$DC_tlt/.winx" w.inx.l
		cp -f "$DC_tlt/.sinx" s.inx.l
		iw=w.inx.l
		is=s.inx.l

		(
		echo "5" ; sleep 0
		echo "# " ; sleep 1

		#=======================================================================imagenes
		
		n=1
		while [[ $n -le "$(cat $iw | wc -l | awk '{print ($1)}')" ]]; do

			wnm=$(sed -n "$n"p $iw)
			
			if [ -f "$DM_tlt/words/images/$wnm.jpg" ]; then
				convert "$DM_tlt/words/images/$wnm.jpg" -alpha set -virtual-pixel transparent \
				-channel A -blur 0x10 -level 50%,100% +channel "$DT/mkhtml/images/$wnm.png"
			fi
			
			let n++
		done
		
		#============================================================== para las oraciones
		
		n=1
		while [[ $n -le "$(cat  $is | wc -l | awk '{print ($1)}')" ]]; do
			wnm=$(sed -n "$n"p $is)
			tgs=$(eyeD3 "$DM_tlt/$wnm.mp3")
			wt=$(echo "$tgs" | grep -o -P "(?<=ISI1I0I).*(?=ISI1I0I)")
			ws=$(echo "$tgs" | grep -o -P "(?<=ISI2I0I).*(?=ISI2I0I)")
			echo "$wt" >> S.gprt.x
			echo "$ws" >> S.gprs.x
			let n++
		done
		
		echo '<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<title>'$tpc'</title>
		<head>
		<style type="text/css">
		h1 {
			margin-top: 0;
			padding-right: 5px;
			padding-left: 5px;
			color: #244D87;
			font-size: 18px;
			font-weight: bold;
			font-family: Verdana, Geneva, sans-serif;
		}
		h2 {
			margin-top: 0;
			padding-right: 5px;
			padding-left: 5px;
			color: #5E823B;
			font-size: 18px;
			font-weight: bold;
			font-family: Verdana, Geneva, sans-serif;
		}
		h3 {
			margin-top: 0;
			padding-right: 5px;
			padding-left: 5px;
			color: #474747;
			font-size: 19px;
			font-weight: bold;
			font-family: Verdana, Geneva, sans-serif;
		}
		}
		mark {
			background-color: #B5DA8F
		}
		.examples {
			width: 80%;
			padding-left: 25px;
			padding-bottom: 10px;
			padding-top: 5px;
			padding-right: 0;
		}
		.ifont {
			color: #3E3E3E;
			font-family: Verdana, Geneva, sans-serif;
			font-size: 12px;
			text-align: left;
		}
		.efont {
			color: #6F6F6F;
			font-family: Verdana, Geneva, sans-serif;
			font-size: 14px;
			text-align: left;
		}
		.nfont {
			color: #6F6F6F;
			font-family: Verdana, Geneva, sans-serif;
			font-size: 10px;
			text-align: left;
		}
		.notasa {
			float: right;
			width: 50%;
			padding-right: 60px;
			font-size: 12px;
			color: #7B7B7B;
		}
		ma {
			margin-top: 0;
			color: #636363;
		}
		a img { 
			border: none;
		}
		.wrds {
			float: left;
			width: 95%;
			padding: 10px 0;
			padding-left: 25px;
			padding-bottom: 120px;
			font-family: Verdana, Geneva, sans-serif;
			font-size: 14px;
			font-weight: bolder;
			color: #666;
		}
		.wrdimg {
			font-family: Verdana, Geneva, sans-serif;
			font-size: 14px;
			font-weight: bold;
			color: #666;
		}
		.wrdstable {
			font-family: Verdana, Geneva, sans-serif;
			font-size: 13px;
			font-weight: bold;
			color: #666;
		}
		.side {
			width: 5px;
		}
		body {
			margin-left: 20px;
			margin-top: 10px;
			margin-right: 10px;
			margin-bottom: 10px;
		}
		</style>
		</head>
		<body>
		<div><p>Created by Idiomind </p>
		</div>
		<div>
		<h3>'$tpc'</h3>
		<table width="80%" align="left" border="0" class="ifont">
		<tr>
		<td>
		'$nts'
		<p>&nbsp;</p>
		<p>&nbsp;</p>
		<p>&nbsp;</p>
		</td>
		</tr>
		</table>' > pdf

		############################### IMAGES  #########################################
		
		cd "$DM_tlt/words/images"
		cnt=`ls -1 *.jpg 2>/dev/null | wc -l`
		
		if [ $cnt != 0 ]; then
		
			cd $DT/mkhtml/images/
			ls *.png | sed 's/\.png//g' > $DT/mkhtml/nimg
			
			cd $DT/mkhtml
			echo '<table width="90%" align="center" border="0" class="wrdimg">' >> pdf
			
			n=1
			while [ $n -le "$(cat nimg | wc -l)" ]; do
				
					if [ -f nnn ]; then
					n=$(cat nnn)
					fi
					
					nn=$(($n + 1))
					nnn=$(($n + 2))
					d1m=$(cat nimg | sed -n "$n","$nn"p | sed -n 1p)
					d2m=$(cat nimg | sed -n "$n","$nn"p | sed -n 2p)
					
					if [ -n "$d1m" ]; then
						
						echo '<tr>
						<td align="center"><img src="images/'$d1m'.png" width="240" height="220"></td>' >> pdf

						if [ -n "$d2m" ]; then
							echo '<td align="center"><img src="images/'$d2m'.png" width="240" height="220"></td>
							</tr>' >> pdf
						else
							echo '</tr>' >> pdf
						fi
						
						echo '<tr>
						<td align="center" valign="top"><p>'$d1m'</p>
						<p>&nbsp;</p>
						<p>&nbsp;</p>
						<p>&nbsp;</p></td>' >> pdf
						
						if [ -n "$d2m" ]; then
							echo '<td align="center" valign="top"><p>'$d2m'</p>
							<p>&nbsp;</p>
							<p>&nbsp;</p>
							<p>&nbsp;</p></td>
							</tr>' >> pdf
						else
							echo '</tr>' >> pdf
						fi
						
					else
						break
					fi
					
					echo $nnn > nnn
				let n++
			done
			
			echo '</table>
			<p>&nbsp;</p>
			<p>&nbsp;</p>' >> pdf
		fi
		
		############################################################### palabras
		cd $DT/mkhtml

		n=1
		while [ $n -le "$(cat $iw | wc -l)" ]; do
			
			wnm=$(sed -n "$n"p $iw)
			tgs=$(eyeD3 "$DM_tlt/words/$wnm.mp3")
			wt=$(echo "$tgs" | grep -o -P "(?<=IWI1I0I).*(?=IWI1I0I)")
			ws=$(echo "$tgs" | grep -o -P "(?<=IWI2I0I).*(?=IWI2I0I)")
			inf=$(echo "$tgs" | grep -o -P '(?<=IWI3I0I).*(?=IWI3I0I)' | tr '_' '\n')
			hlgt=$(echo $wt | awk '{print tolower($0)}')
			exm1=$(echo "$inf" | sed -n 1p | sed 's/\\n/ /g')
			dftn=$(echo "$inf" | sed -n 2p | sed 's/\\n/ /g')
			ntes=$(echo "$inf" | sed -n 3p | sed 's/\\n/ /g')
			
			exmp1=$(echo "$exm1" \
			| sed "s/"$hlgt"/<b>"$hlgt"<\/\b>/g")
			
			echo "$wt" >> W.lizt.x
			echo "$ws" >> W.lizs.x
			
			if [ -n "$wt" ]; then
			
				echo '<table width="55%" border="0" align="left" cellpadding="10" cellspacing="5">
				<tr>
				<td bgcolor="#9FBFF8" class="side"></td>
				<td bgcolor="#E7EFFD"><h1>'$wt'</h1></td>
				</tr>
				<tr>
				<td bgcolor="#B5DA8F" class="side"></td>
				<td bgcolor="#F4FFE9"><h2>'$ws'</h2></td>
				</tr>
				</table>' >> pdf
				
				echo '<table width="100%" border="0" align="center" cellpadding="10" class="efont">
				<tr>
				<td width="10px"></td>' >> pdf
				
				if ([ -z "$dftn" ] && [ -z "$exmp1" ]); then
				
				echo '<td width="466" valign="top" class="nfont" >'$ntes'</td>
				<td width="389"</td>
				</tr>
				</table>' >> pdf
				
				else
					echo '<td width="466">' >> pdf
					
					if [ -n "$dftn" ]; then
						echo '<dl>
						<dt>Definition:</dt>
						<dd><dfn>'$dftn'</dfn></dd>
						</dl>' >> pdf
					fi
					
					if [ -n "$exmp1" ]; then
						echo '<dl>
						<dt>Example:</dt>
						<dd><cite>'$exmp1'</cite></dd>
						</dl>' >> pdf
					fi 
					
					echo '</td>
					<td width="389" valign="top" class="nfont">'$ntes'</td>
					</tr>
					</table>' >> pdf
				fi
				
				echo '<p>&nbsp;</p>
				<h1>&nbsp;</h1>' >> pdf
			fi
			let n++
		done
				
		######################################################## oraciones
		
		n=1
		while [ $n -le "$(cat s.inx.l | wc -l)" ]; do
				
				st=$(sed -n "$n"p S.gprt.x)
				
				if [ -n "$st" ]; then

					ss=$(sed -n "$n"p S.gprs.x)
					fn=$(sed -n "$n"p s.inx.l)
				
					echo '<table width="100%" border="0" align="left" cellpadding="10" cellspacing="5">
					<tr>
					<td bgcolor="#9FBFF8" class="side">&nbsp;</td>
					<td bgcolor="#E7EFFD"><h1>'$st'</h1></td>
					</tr>' > Sgprt.tmp
					echo '<tr>
					<td bgcolor="#B5DA8F" class="side">&nbsp;</td>
					<td bgcolor="#F4FFE9"><h2>'$ss'</h2></td>
					</tr>
					</table>' > Sgprs.tmp
					
					echo '<div class="wrds">
					<table width="40%" align="left" cellpadding="5" class="wrdstable">
					<tbody>' > Wgprs.tmp
						
					eyeD3 "$DM_tlt/$fn.mp3" > tgs
					> wt
					> ws
					(
					n=1
					while [ $n -le "$(echo "$st" | sed 's/ /\n/g' \
					| grep -v '^.$' | grep -v '^..$' | wc -l)" ]; do
						cat tgs | grep -o -P '(?<=ISTI'$n'I0I).*(?=ISTI'$n'I0I)' >> wt
						cat tgs | grep -o -P '(?<=ISSI'$n'I0I).*(?=ISSI'$n'I0I)' >> ws
						let n++
					done
					)
			
					(
					n=1
					while [ $n -le "$(cat wt | wc -l)" ]; do
						wt=$(sed -n "$n"p wt)
						ws=$(sed -n "$n"p ws)
						wt2=$(sed -n "$n"p wt)
						
						if cat W.lizt.x | grep "$wt2"; then
							echo '<tr>
							<td bgcolor="#9FBFF8"><ma>'$wt'</ma></td>
							<td bgcolor="#B5DA8F"><ma>'$ws'</ma></td>
							</tr>' >> ./Wgprs.tmp
						else
							echo '<tr>
							<td bgcolor="#E7EFFD">'$wt'</td>
							<td bgcolor="#F4FFE9">'$ws'</td>
							</tr>' >> ./Wgprs.tmp
						fi
						
						let n++
					done
					)
					
					echo '</tbody>
					</table>
					</div>
					<p>&nbsp;</p>
					<p>&nbsp;</p>
					<h1>&nbsp;</h1>' >> Wgprs.tmp
					
					#echo '</tbody>
					#</table>
					    #<table width="40%" border="0" align="right">
						#<tr align="center" valign="top">
						#<td><p>   <img src="./images/Until.png" width="360" height="240" align="middle"></p></td>
						#</tr>
					#</table>
					#</div>
					#<p>&nbsp;</p>
					#<p>&nbsp;</p>
					#<h1>&nbsp;</h1>' >> Wgprs.tmp

					cat Sgprt.tmp >> pdf
					cat Sgprs.tmp >> pdf
					cat Wgprs.tmp >> pdf
				fi
			let n++
		done
		
		# =======================================  - - - - -   html de topic
		
		echo '<p>&nbsp;</p>
		<p>&nbsp;</p>
		<h3>&nbsp;</h3>
		<p>&nbsp;</p>
		</div>
		</div>
		<span class="container"></span>
		</body>
		</html>' >> pdf
		mv -f pdf pdf.html
		wkhtmltopdf -s A4 -O Portrait --ignore-load-errors pdf.html tmp.pdf
		mv -f tmp.pdf "$pdf"
		
		rm -fr pdf $DT/mkhtml $DT/*.x $DT/*.l
		
		) | $yad --progress \
		--width=20 --height=20 --geometry=20x20-2-2 \
		--pulsate --percentage="5" --auto-close \
		--sticky --on-top --undecorated \
		--skip-taskbar --center --no-buttons exit
	else
		exit 1
	fi
fi
