#!/bin/bash

source /usr/share/idiomind/ifs/c.conf
if [ -f "$DM_tl/Feeds/conten/$1.mp3" ]; then
	drtx="$DM_tl/Feeds/conten"
elif [ -f "$DM_tl/Feeds/kept/$1.mp3" ]; then
	drtx="$DM_tl/Feeds/kept"
fi
sleep 0.5
if [[ "$(ps -A | grep -o "plwd")" = "plwd" ]]; then
	exit 1
else
	if [[ "$(ps -A | grep -o "play")" = "play" ]]; then
		exit 1
	fi
	play "$drtx/$1.mp3" & sleep 0.2 && exit 1
fi

