#!/bin/bash

source /usr/share/idiomind/ifs/c.conf
if [ -f "$DM_tl/Feeds/conten/$1.mp3" ]; then
	drtx="$DM_tl/Feeds/conten/$1"
	fle="$DM_tl/Feeds/conten/$1.mp3"
elif [ -f "$DM_tl/Feeds/kept/$1.mp3" ]; then
	drtx="$DM_tl/Feeds/kept/.audio"
	fle="$DM_tl/Feeds/kept/$1.mp3"
else
	exit 1
fi

killall play
file="$fle"
lwrd=$(eyeD3 "$file" | grep -o -P '(?<=ISI1I0I).*(?=ISI1I0I)' \
| awk '{print tolower($0)}' | tr ' ' '\n')

n=1
while [ $n -le "$(echo "$lwrd" | wc -l)" ]; do
	ply=$(echo "$lwrd" | sed -n "$n"p)
	play "$drtx/$ply.mp3"
	let n++
done
exit 1
