#!/bin/bash
killall prct
killall play
DS_pp=/usr/share/idiomind/addons/Practice
tpc=$(sed -n 1p $HOME/.config/idiomind/s/topic.id)
lgtl=$(sed -n 2p $HOME/.config/idiomind/s/lang)
DIR2="$HOME/.config/idiomind/topics/$lgtl/$tpc/Practice"
DIR3="$HOME/.config/idiomind/topics/$lgtl/$tpc"
w9="$HOME/.config/idiomind/addons/practice/w9"
w6="$HOME/.config/idiomind/addons/practice/w6"
cd "$DIR2"

if [ "$1" = df ]; then
	
	rm look_f *.id *.no *.ok fin1 fin2 fin3 iF
	echo "1" > .iconf
	echo "0" > f_r
	$DS_pp/strt &
	exit 1
	
elif [ "$1" = dm ]; then
	
	rm look_mc *.id *.no *.ok mcin1 mcin2 mcin3 iMC word1.idx
	echo "1" > .iconmc
	echo "0" > mc_r
	$DS_pp/strt &
	exit 1
	
elif [ "$1" = dw ]; then
	
	rm look_lw *.id *.no *.ok lwin iLW
	echo "1" > .iconlw
	echo "0" > lw_r
	$DS_pp/strt &
	exit 1
	
elif [ "$1" = ds ]; then
	
	rm look_ls *.id *.no *.ok lsin lsin.tmp iLC
	echo "1" > .iconls
	echo "0" > ls_r
	$DS_pp/strt &
	exit 1
	
	
elif [ "$2" = f ]; then
	
	killall df.sh
	cat *.no >> "$w6"
	cat *.ok >> "$w9"
	echo "$(grep -F -x -v -f fin.ok fin.no | sort -u | uniq | wc -l)" > no.id
	echo "$(cat fin.ok | wc -l)" > ok.id
	cat ./fin.ok >> iF
	echo "$(cat iF | wc -l)" > f_r
	var1=$((100*$(cat f_r)/$(cat idxfin)))
	
	if [ $var1 -lt 1 ]; then
		echo 1 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 1 ]; then
		echo 1 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 5 ]; then
		echo 2 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 10 ]; then
		echo 3 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 15 ]; then
		echo 4 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 20 ]; then
		echo 5 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 25 ]; then
		echo 6 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 30 ]; then
		echo 7 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 35 ]; then
		echo 8 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 40 ]; then
		echo 9 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 45 ]; then
		echo 10 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 50 ]; then
		echo 11 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 55 ]; then
		echo 12 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 60 ]; then
		echo 13 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 65 ]; then
		echo 14 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 70 ]; then
		echo 15 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 75 ]; then
		echo 16 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 80 ]; then
		echo 17 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 85 ]; then
		echo 18 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 90 ]; then
		echo 19 > "$DIR2"/.iconf
	
	elif [ $var1 -lt 95 ]; then
		echo 20 > "$DIR2"/.iconf
	
	elif [ $var1 -eq 100 ]; then
		echo 21 > "$DIR2"/.iconf
	fi
	
	$DS_pp/strt 5
	
	exit

elif [ "$2" = m ]; then

	killall dmc.sh
	cat *.no >> "$w6"
	cat *.ok >> "$w9"
	echo "$(grep -F -x -v -f mcin.ok mcin.no | sort -u | uniq | wc -l)" > no.id
	echo "$(cat mcin.ok | wc -l)" > ok.id
	cat mcin.ok >> iMC
	echo "$(cat iMC | wc -l)" > mc_r
	var3=$((100*$(cat "$DIR2"/mc_r)/$(cat idxmcin)))
	
	if [ $var3 -lt 1 ]; then
		echo 1 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 5 ]; then
		echo 2 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 10 ]; then
		echo 3 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 15 ]; then
		echo 4 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 20 ]; then
		echo 5 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 25 ]; then
		echo 6 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 30 ]; then
		echo 7 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 35 ]; then
		echo 8 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 40 ]; then
		echo 9 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 45 ]; then
		echo 10 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 50 ]; then
		echo 11 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 55 ]; then
		echo 12 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 60 ]; then
		echo 13 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 65 ]; then
		echo 14 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 70 ]; then
		echo 15 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 75 ]; then
		echo 16 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 80 ]; then
		echo 17 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 85 ]; then
		echo 18 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 90 ]; then
		echo 19 > "$DIR2"/.iconmc
	
	elif [ $var3 -lt 95 ]; then
		echo 20 > "$DIR2"/.iconmc
	
	elif [ $var3 -eq 100 ]; then
		echo 21 > "$DIR2"/.iconmc
	fi
	
	$DS_pp/strt 6
	
	exit

elif [ "$2" = w ]; then

	killall dlw.sh
	cat lwin.no >> "$w6"
	cat lwin.ok >> "$w9"
	echo "$(grep -F -x -v -f lwin.ok lwin.no | sort -u | uniq | wc -l)" > no.id
	echo "$(cat lwin.ok | wc -l)" > ok.id
	cat lwin.ok >> iLW
	echo "$(cat iLW | wc -l)" > lw_r
	var2=$((100*$(cat lw_r)/$(cat idxlwin)))
	
	if [ $var2 -lt 1 ]; then
		echo 1 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 5 ]; then
		echo 2 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 10 ]; then
		echo 3 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 15 ]; then
		echo 4 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 20 ]; then
		echo 5 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 25 ]; then
		echo 6 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 30 ]; then
		echo 7 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 35 ]; then
		echo 8 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 40 ]; then
		echo 9 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 45 ]; then
		echo 10 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 50 ]; then
		echo 11 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 55 ]; then
		echo 12 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 60 ]; then
		echo 13 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 65 ]; then
		echo 14 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 70 ]; then
		echo 15 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 75 ]; then
		echo 16 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 80 ]; then
		echo 17 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 85 ]; then
		echo 18 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 90 ]; then
		echo 19 > "$DIR2"/.iconlw
	
	elif [ $var2 -lt 95 ]; then
		echo 20 > "$DIR2"/.iconlw
	
	elif [ $var2 -eq 100 ]; then
		echo 21 > "$DIR2"/.iconlw
	fi
	
	$DS_pp/strt 7
	
	exit


elif [ "$1" = s ]; then
	
	killall dls.sh
	echo "$(grep -F -x -v -f lsin.ok lsin.no | sort -u | uniq | wc -l)" > no.id
	echo "$(cat lsin.ok | wc -l)" > ok.id
	cat ./lsin.ok >> iLS
	echo "$(cat iLS | wc -l)" > ls_r
	var4=$((100*$(cat ls_r)/$(cat idxlsin)))
	
	if [ $var4 -lt 1 ]; then
		echo 1 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 5 ]; then
		echo 2 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 10 ]; then
		echo 3 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 15 ]; then
		echo 4 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 20 ]; then
		echo 5 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 25 ]; then
		echo 6 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 30 ]; then
		echo 7 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 35 ]; then
		echo 8 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 40 ]; then
		echo 9 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 45 ]; then
		echo 10 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 50 ]; then
		echo 11 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 55 ]; then
		echo 12 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 60 ]; then
		echo 13 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 65 ]; then
		echo 14 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 70 ]; then
		echo 15 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 75 ]; then
		echo 16 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 80 ]; then
		echo 17 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 85 ]; then
		echo 18 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 90 ]; then
		echo 19 > "$DIR2"/.iconls
	
	elif [ $var4 -lt 95 ]; then
		echo 20 > "$DIR2"/.iconls
	
	elif [ $var4 -eq 100 ]; then
		echo 21 > "$DIR2"/.iconls
	
	fi
	
	$DS_pp/strt 8
	
	exit
fi
