#!/bin/bash

killall prct
killall play
DSP=/usr/share/idiomind/addons/Practice
tpc=$(sed -n 1p $HOME/.config/idiomind/s/cnfg8)
lgtl=$(sed -n 2p $HOME/.config/idiomind/s/cnfg10)
DIR2="$HOME/.config/idiomind/topics/$lgtl/$tpc/Practice"
DIR3="$HOME/.config/idiomind/topics/$lgtl/$tpc"
w9="$HOME/.config/idiomind/addons/practice/w9"
w6="$HOME/.config/idiomind/addons/practice/w6"
cd "$DIR2"

if [ "$1" = df ]; then
	rm look_f *.no *.ok fin1 fin2 fin3 iF
	echo "1" > .iconf
	echo "0" > f_r
	$DSP/strt &
	exit 1
elif [ "$1" = dm ]; then
	rm look_mc *.no *.ok mcin1 mcin2 mcin3 iMC word1.idx
	echo "1" > .iconmc
	echo "0" > mc_r
	$DSP/strt &
	exit 1
elif [ "$1" = dw ]; then
	rm look_lw *.no *.ok lwin iLW
	echo "1" > .iconlw
	echo "0" > lw_r
	$DSP/strt &
	exit 1
elif [ "$1" = ds ]; then
	rm look_ls *.no *.ok lsin lsin.tmp iLC
	echo "1" > .iconls
	echo "0" > ls_r
	$DSP/strt &
	exit 1
fi
	
if [ "$2" = f ]; then

	killall df.sh
	cd "$DIR2"
	[[ ! -f fin.$1.ok ]] && touch fin.$1.ok
	[[ ! -f fin.$1.no ]] && touch fin.$1.no
	cat fin.$1.no >> "$w6"
	cat fin.$1.ok >> "$w9"
	s2=$(cat fin.$1.ok | wc -l)
	if [ -f f_r ]; then
		s1=$(cat f_r)
		s3=$(($s1+$s2))
		echo $s3 > f_r
	else
		s1=1
		s3=$(($s1+$s2))
		echo "$(($s3-1))" > f_r
	fi

	s4=$(cat idxfin)
	var1=$((100*$s1/$s4))

	if [ $var1 -lt 1 ]; then
		echo 1 > .iconf
	elif [ $var1 -lt 5 ]; then
		echo 2 > .iconf
	elif [ $var1 -lt 10 ]; then
		echo 3 > .iconf
	elif [ $var1 -lt 15 ]; then
		echo 4 > .iconf
	elif [ $var1 -lt 20 ]; then
		echo 5 > .iconf
	elif [ $var1 -lt 25 ]; then
		echo 6 > .iconf
	elif [ $var1 -lt 30 ]; then
		echo 7 > .iconf
	elif [ $var1 -lt 35 ]; then
		echo 8 > .iconf
	elif [ $var1 -lt 40 ]; then
		echo 9 > .iconf
	elif [ $var1 -lt 45 ]; then
		echo 10 > .iconf
	elif [ $var1 -lt 50 ]; then
		echo 11 > .iconf
	elif [ $var1 -lt 55 ]; then
		echo 12 > .iconf
	elif [ $var1 -lt 60 ]; then
		echo 13 > .iconf
	elif [ $var1 -lt 65 ]; then
		echo 14 > .iconf
	elif [ $var1 -lt 70 ]; then
		echo 15 > .iconf
	elif [ $var1 -lt 75 ]; then
		echo 16 > .iconf
	elif [ $var1 -lt 80 ]; then
		echo 17 > .iconf
	elif [ $var1 -lt 85 ]; then
		echo 18 > .iconf
	elif [ $var1 -lt 90 ]; then
		echo 19 > .iconf
	elif [ $var1 -lt 95 ]; then
		echo 20 > .iconf
	elif [ $var1 -eq 100 ]; then
		echo 21 > .iconf
	fi
	$DSP/strt 5 "$1" & exit 1

elif [ "$2" = m ]; then

	killall dmc.sh
	cd "$DIR2"
	[[ ! -f mcin.$1.ok ]] && touch mcin.$1.ok
	[[ ! -f mcin.$1.no ]] && touch mcin.$1.no
	cat mcin.$1.no >> "$w6"
	cat mcin.$1.ok >> "$w9"
	s2=$(cat mcin.$1.ok | wc -l)
	if [ -f mc_r ]; then
		s1=$(cat mc_r)
		s3=$(($s1+$s2))
		echo $s3 > mc_r
	else
		s1=1
		s3=$(($s1+$s2))
		echo "$(($s3-1))" > mc_r
	fi
	s4=$(cat idxmcin)
	var3=$((100*$s1/$s4))
	
	if [ $var3 -lt 1 ]; then
		echo 1 > .iconmc
	elif [ $var3 -lt 5 ]; then
		echo 2 > .iconmc
	elif [ $var3 -lt 10 ]; then
		echo 3 > .iconmc
	elif [ $var3 -lt 15 ]; then
		echo 4 > .iconmc
	elif [ $var3 -lt 20 ]; then
		echo 5 > .iconmc
	elif [ $var3 -lt 25 ]; then
		echo 6 > .iconmc
	elif [ $var3 -lt 30 ]; then
		echo 7 > .iconmc
	elif [ $var3 -lt 35 ]; then
		echo 8 > .iconmc
	elif [ $var3 -lt 40 ]; then
		echo 9 > .iconmc
	elif [ $var3 -lt 45 ]; then
		echo 10 > .iconmc
	elif [ $var3 -lt 50 ]; then
		echo 11 > .iconmc
	elif [ $var3 -lt 55 ]; then
		echo 12 > .iconmc
	elif [ $var3 -lt 60 ]; then
		echo 13 > .iconmc
	elif [ $var3 -lt 65 ]; then
		echo 14 > .iconmc
	elif [ $var3 -lt 70 ]; then
		echo 15 > .iconmc
	elif [ $var3 -lt 75 ]; then
		echo 16 > .iconmc
	elif [ $var3 -lt 80 ]; then
		echo 17 > .iconmc
	elif [ $var3 -lt 85 ]; then
		echo 18 > .iconmc
	elif [ $var3 -lt 90 ]; then
		echo 19 > .iconmc
	elif [ $var3 -lt 95 ]; then
		echo 20 > .iconmc
	elif [ $var3 -eq 100 ]; then
		echo 21 > .iconmc
	fi
	$DSP/strt 6 "$1" & exit 1

elif [ "$2" = w ]; then

	killall dlw.sh
	cd "$DIR2"
	[[ ! -f lwin.$1.ok ]] && touch lwin.$1.ok
	[[ ! -f lwin.$1.no ]] && touch lwin.$1.no
	cat lwin.$1.no >> "$w6"
	cat lwin.$1.ok >> "$w9"
	s2=$(cat lwin.$1.ok | wc -l)
	if [ -f lw_r ]; then
		s1=$(cat lw_r)
		s3=$(($s1+$s2))
		echo $s3 > lw_r
	else
		s1=1
		s3=$(($s1+$s2))
		echo "$(($s3-1))" > lw_r
	fi
	s4=$(cat idxlwin)
	var2=$((100*$s1/$s4))
	
	if [ $var2 -lt 1 ]; then
		echo 1 > .iconlw
	elif [ $var2 -lt 5 ]; then
		echo 2 > .iconlw
	elif [ $var2 -lt 10 ]; then
		echo 3 > .iconlw
	elif [ $var2 -lt 15 ]; then
		echo 4 > .iconlw
	elif [ $var2 -lt 20 ]; then
		echo 5 > .iconlw
	elif [ $var2 -lt 25 ]; then
		echo 6 > .iconlw
	elif [ $var2 -lt 30 ]; then
		echo 7 > .iconlw
	elif [ $var2 -lt 35 ]; then
		echo 8 > .iconlw
	elif [ $var2 -lt 40 ]; then
		echo 9 > .iconlw
	elif [ $var2 -lt 45 ]; then
		echo 10 > .iconlw
	elif [ $var2 -lt 50 ]; then
		echo 11 > .iconlw
	elif [ $var2 -lt 55 ]; then
		echo 12 > .iconlw
	elif [ $var2 -lt 60 ]; then
		echo 13 > .iconlw
	elif [ $var2 -lt 65 ]; then
		echo 14 > .iconlw
	elif [ $var2 -lt 70 ]; then
		echo 15 > .iconlw
	elif [ $var2 -lt 75 ]; then
		echo 16 > .iconlw
	elif [ $var2 -lt 80 ]; then
		echo 17 > .iconlw
	elif [ $var2 -lt 85 ]; then
		echo 18 > .iconlw
	elif [ $var2 -lt 90 ]; then
		echo 19 > .iconlw
	elif [ $var2 -lt 95 ]; then
		echo 20 > .iconlw
	elif [ $var2 -eq 100 ]; then
		echo 21 > .iconlw
	fi
	$DSP/strt 7 "$1" & exit 1

elif [ "$1" = s ]; then

	killall dls.sh
	cd "$DIR2"
	[[ ! -f lsin.ok ]] && touch lsin.ok
	[[ ! -f lsin.no ]] && touch lsin.no
	[[ ! -f lsin.1.no ]] && touch lsin.1.no
	cat lsin.1.no >> "$w6"
	cat lsin.no >> "$w6"
	cat lsin.ok >> "$w9"
	s2=$(cat lsin.ok | wc -l)
	if [ -f ls_r ]; then
		s1=$(cat ls_r)
		s3=$(($s1+$s2))
		echo $s3 > ls_r
	else
		s1=1
		s3=$(($s1+$s2))
		echo "$(($s3-1))" > ls_r
	fi
	s4=$(cat idxlsin)
	var4=$((100*$s1/$s4))
	
	if [ $var4 -lt 1 ]; then
		echo 1 > .iconls
	elif [ $var4 -lt 5 ]; then
		echo 2 > .iconls
	elif [ $var4 -lt 10 ]; then
		echo 3 > .iconls
	elif [ $var4 -lt 15 ]; then
		echo 4 > .iconls
	elif [ $var4 -lt 20 ]; then
		echo 5 > .iconls
	elif [ $var4 -lt 25 ]; then
		echo 6 > .iconls
	elif [ $var4 -lt 30 ]; then
		echo 7 > .iconls
	elif [ $var4 -lt 35 ]; then
		echo 8 > .iconls
	elif [ $var4 -lt 40 ]; then
		echo 9 > .iconls
	elif [ $var4 -lt 45 ]; then
		echo 10 > .iconls
	elif [ $var4 -lt 50 ]; then
		echo 11 > .iconls
	elif [ $var4 -lt 55 ]; then
		echo 12 > .iconls
	elif [ $var4 -lt 60 ]; then
		echo 13 > .iconls
	elif [ $var4 -lt 65 ]; then
		echo 14 > .iconls
	elif [ $var4 -lt 70 ]; then
		echo 15 > .iconls
	elif [ $var4 -lt 75 ]; then
		echo 16 > .iconls
	elif [ $var4 -lt 80 ]; then
		echo 17 > .iconls
	elif [ $var4 -lt 85 ]; then
		echo 18 > .iconls
	elif [ $var4 -lt 90 ]; then
		echo 19 > .iconls
	elif [ $var4 -lt 95 ]; then
		echo 20 > .iconls
	elif [ $var4 -eq 100 ]; then
		echo 21 > .iconls
	fi
	$DSP/strt 8 & exit 1
fi
