#!/bin/bash

killall prct
killall play
DSP=/usr/share/idiomind/addons/Practice
tpc=$(sed -n 1p $HOME/.config/idiomind/s/cnfg8)
lgtl=$(sed -n 2p $HOME/.config/idiomind/s/cnfg10)
DIR2="$HOME/.config/idiomind/topics/$lgtl/$tpc/Practice"
DIR3="$HOME/.config/idiomind/topics/$lgtl/$tpc"
w9="$HOME/.config/idiomind/addons/practice/w9"
w6="$HOME/.config/idiomind/addons/practice/w6"
cd "$DIR2"

if [ "$1" = df ]; then
	rm look_f fin fin1 fin2 fin3 ok.f
	echo "1" > .iconf
	echo "0" > l_f
	$DSP/strt &
	exit 1
elif [ "$1" = dm ]; then
	rm look_mc *.no *.ok mcin1 mcin2 mcin3 iMC word1.idx
	echo "1" > .iconmc
	echo "0" > mc_r
	$DSP/strt &
	exit 1
elif [ "$1" = dw ]; then
	rm look_lw lwin lwin1 lwin2 lwin3 ok.w
	echo "1" > .iconlw
	echo "0" > l_lw
	$DSP/strt &
	exit 1
elif [ "$1" = ds ]; then
	rm look_ls *.no *.ok lsin lsin.tmp iLC
	echo "1" > .iconls
	echo "0" > ls_r
	$DSP/strt &
	exit 1
fi
	
if [ "$1" = f ]; then

	killall $DSP/df.sh
	killall $DSP/prct
	killall $DSP/strt
	cd "$DIR2"
	
	easy=$2
	ling=$3
	hard=$4
	all=$5
	
	[[ -f ok.f ]] && cat ok.f >> "$w9"
	[[ -f l_f ]] && echo $(($(cat l_f)+$easy)) > l_f || echo $easy > l_f
	s=$(cat l_f)
	v=$((100*$s/$all))

	if [ $v -le 1 ]; then
		echo 1 > .iconf
	elif [ $v -le 5 ]; then
		echo 2 > .iconf
	elif [ $v -le 10 ]; then
		echo 3 > .iconf
	elif [ $v -le 15 ]; then
		echo 4 > .iconf
	elif [ $v -le 20 ]; then
		echo 5 > .iconf
	elif [ $v -le 25 ]; then
		echo 6 > .iconf
	elif [ $v -le 30 ]; then
		echo 7 > .iconf
	elif [ $v -le 35 ]; then
		echo 8 > .iconf
	elif [ $v -le 40 ]; then
		echo 9 > .iconf
	elif [ $v -le 45 ]; then
		echo 10 > .iconf
	elif [ $v -le 50 ]; then
		echo 11 > .iconf
	elif [ $v -le 55 ]; then
		echo 12 > .iconf
	elif [ $v -le 60 ]; then
		echo 13 > .iconf
	elif [ $v -le 65 ]; then
		echo 14 > .iconf
	elif [ $v -le 70 ]; then
		echo 15 > .iconf
	elif [ $v -le 75 ]; then
		echo 16 > .iconf
	elif [ $v -le 80 ]; then
		echo 17 > .iconf
	elif [ $v -le 85 ]; then
		echo 18 > .iconf
	elif [ $v -le 90 ]; then
		echo 19 > .iconf
	elif [ $v -le 95 ]; then
		echo 20 > .iconf
	elif [ $v -eq 100 ]; then
		echo 21 > .iconf
	fi
	
	$DSP/strt 5 $easy $ling $hard & exit 1

elif [ "$1" = m ]; then

	killall dmc.sh
	cd "$DIR2"
	
	easy=$2
	ling=$3
	hard=$4
	all=$5
	
	[[ -f ok.m ]] && cat ok.m >> "$w9"
	[[ -f l_mc ]] && echo $(($(cat l_mc)+$easy)) > l_mc || echo $easy > l_mc
	s=$(cat l_mc)
	v=$((100*$s/$all))

	if [ $v -le 1 ]; then
		echo 1 > .iconmc
	elif [ $v -le 5 ]; then
		echo 2 > .iconmc
	elif [ $v -le 10 ]; then
		echo 3 > .iconmc
	elif [ $v -le 15 ]; then
		echo 4 > .iconmc
	elif [ $v -le 20 ]; then
		echo 5 > .iconmc
	elif [ $v -le 25 ]; then
		echo 6 > .iconmc
	elif [ $v -le 30 ]; then
		echo 7 > .iconmc
	elif [ $v -le 35 ]; then
		echo 8 > .iconmc
	elif [ $v -le 40 ]; then
		echo 9 > .iconmc
	elif [ $v -le 45 ]; then
		echo 10 > .iconmc
	elif [ $v -le 50 ]; then
		echo 11 > .iconmc
	elif [ $v -le 55 ]; then
		echo 12 > .iconmc
	elif [ $v -le 60 ]; then
		echo 13 > .iconmc
	elif [ $v -le 65 ]; then
		echo 14 > .iconmc
	elif [ $v -le 70 ]; then
		echo 15 > .iconmc
	elif [ $v -le 75 ]; then
		echo 16 > .iconmc
	elif [ $v -le 80 ]; then
		echo 17 > .iconmc
	elif [ $v -le 85 ]; then
		echo 18 > .iconmc
	elif [ $v -le 90 ]; then
		echo 19 > .iconmc
	elif [ $v -le 95 ]; then
		echo 20 > .iconmc
	elif [ $v -eq 100 ]; then
		echo 21 > .iconmc
	fi

	$DSP/strt 6 $easy $ling $hard & exit 1

elif [ "$1" = w ]; then

	killall dlw.sh
	cd "$DIR2"
	cd "$DIR2"
	
	easy=$2
	ling=$3
	hard=$4
	all=$5
	
	[[ -f ok.w ]] && cat ok.w >> "$w9"
	[[ -f l_lw ]] && echo $(($(cat l_lw)+$easy)) > l_lw || echo $easy > l_lw
	s=$(cat l_lw)
	v=$((100*$s/$all))
	
	if [ $v -le 1 ]; then
		echo 1 > .iconlw
	elif [ $v -le 5 ]; then
		echo 2 > .iconlw
	elif [ $v -le 10 ]; then
		echo 3 > .iconlw
	elif [ $v -le 15 ]; then
		echo 4 > .iconlw
	elif [ $v -le 20 ]; then
		echo 5 > .iconlw
	elif [ $v -le 25 ]; then
		echo 6 > .iconlw
	elif [ $v -le 30 ]; then
		echo 7 > .iconlw
	elif [ $v -le 35 ]; then
		echo 8 > .iconlw
	elif [ $v -le 40 ]; then
		echo 9 > .iconlw
	elif [ $v -le 45 ]; then
		echo 10 > .iconlw
	elif [ $v -le 50 ]; then
		echo 11 > .iconlw
	elif [ $v -le 55 ]; then
		echo 12 > .iconlw
	elif [ $v -le 60 ]; then
		echo 13 > .iconlw
	elif [ $v -le 65 ]; then
		echo 14 > .iconlw
	elif [ $v -le 70 ]; then
		echo 15 > .iconlw
	elif [ $v -le 75 ]; then
		echo 16 > .iconlw
	elif [ $v -le 80 ]; then
		echo 17 > .iconlw
	elif [ $v -le 85 ]; then
		echo 18 > .iconlw
	elif [ $v -le 90 ]; then
		echo 19 > .iconlw
	elif [ $v -le 95 ]; then
		echo 20 > .iconlw
	elif [ $v -eq 100 ]; then
		echo 21 > .iconlw
	fi
	
	$DSP/strt 7 $easy $ling $hard & exit 1

elif [ "$1" = s ]; then

	killall dls.sh
	cd "$DIR2"
	[[ ! -f lsin.ok ]] && touch lsin.ok
	[[ ! -f lsin.no ]] && touch lsin.no
	[[ ! -f lsin.1.no ]] && touch lsin.1.no
	cat lsin.1.no >> "$w6"
	cat lsin.no >> "$w6"
	cat lsin.ok >> "$w9"
	s2=$(cat lsin.ok | wc -l)
	if [ -f ls_r ]; then
		s1=$(cat ls_r)
		s3=$(($s1+$s2))
		echo $s3 > ls_r
	else
		s1=1
		s3=$(($s1+$s2))
		echo "$(($s3-1))" > ls_r
	fi
	s4=$(cat idxlsin)
	var4=$((100*$s1/$s4))
	
	if [ $var4 -lt 1 ]; then
		echo 1 > .iconls
	elif [ $var4 -lt 5 ]; then
		echo 2 > .iconls
	elif [ $var4 -lt 10 ]; then
		echo 3 > .iconls
	elif [ $var4 -lt 15 ]; then
		echo 4 > .iconls
	elif [ $var4 -lt 20 ]; then
		echo 5 > .iconls
	elif [ $var4 -lt 25 ]; then
		echo 6 > .iconls
	elif [ $var4 -lt 30 ]; then
		echo 7 > .iconls
	elif [ $var4 -lt 35 ]; then
		echo 8 > .iconls
	elif [ $var4 -lt 40 ]; then
		echo 9 > .iconls
	elif [ $var4 -lt 45 ]; then
		echo 10 > .iconls
	elif [ $var4 -lt 50 ]; then
		echo 11 > .iconls
	elif [ $var4 -lt 55 ]; then
		echo 12 > .iconls
	elif [ $var4 -lt 60 ]; then
		echo 13 > .iconls
	elif [ $var4 -lt 65 ]; then
		echo 14 > .iconls
	elif [ $var4 -lt 70 ]; then
		echo 15 > .iconls
	elif [ $var4 -lt 75 ]; then
		echo 16 > .iconls
	elif [ $var4 -lt 80 ]; then
		echo 17 > .iconls
	elif [ $var4 -lt 85 ]; then
		echo 18 > .iconls
	elif [ $var4 -lt 90 ]; then
		echo 19 > .iconls
	elif [ $var4 -lt 95 ]; then
		echo 20 > .iconls
	elif [ $var4 -eq 100 ]; then
		echo 21 > .iconls
	fi
	$DSP/strt 8 & exit 1
fi
