#!/bin/bash
tpc=$(sed -n 1p ~/.config/idiomind/s/topic.id)
lgtl=$(sed -n 2p ~/.config/idiomind/s/lang)
drtt="$HOME/.idiomind/topics/$lgtl/$tpc/words"
drtu="/usr/share/idiomind/addons/Practice/"
cd "$HOME/.config/idiomind/topics/$lgtl/$tpc/Practice"
yad=yad
vww=$drtu/lrng
e=$1

nm=$(sed -n "$1"p stp"$2")
if [ -z "$nm" ]; then
	nm=$(sed -n 1p stp"$2")
	e=1
fi
file="$drtt/$nm.mp3"
vw="$3"

B=$(echo "$vw" | sed -n 1p) 
if [ $B = TRUE ]; then
	aut=--timeout=2
fi

prn=play


wrds=$(cat stp"$2" | awk 1 ORS='   ')
vsw=$(echo "$wrds" | sed "s#${nm}#<big><big><big><big><big><big> \
${nm} <\/\big><\/\big><\/\big><\/\big><\/\big><\/\big>#g")
srce=$(eyeD3 "$file" | grep -o -P '(?<=IWI2I0I).*(?=IWI2I0I)')

listen="play '$file'"
stp="$drtu/stp.sh"
play="play '$file'"

(
sleep 0.3
"$prn" "$file"
) &

vw=$($yad --form --always-print-result --window-icon=idiomind \
--center --separator="\\n" --columns=1 --name=idiomind \
--width=420 --height=250 --on-top --skip-taskbar --fixed \
--borders=15 --align=right --class=idiomind $aut \
--buttons-layout=center --title=" " --undecorated \
--text-align=center \
--field="Auto":chk "$B" \
--button="Practice:$stp" \
--button="Listen:"$play"" \
--button=">:2" \
--text="$vsw\\n\\n <i><big><big>\
<span color='#7F7F7F'>[ </span> \
<span color='#8B9299'><big><big><b> $srce </b></big></big></span> \
<span color='#7F7F7F'> ]</span></big></big></i> \\n\\n")

	ret=$?
	if [[ $ret -eq 2 ]]; then
		ff=$(($e + 1))
		$vww "$ff" "$2" "$vw"
	elif [[ $ret -eq 3 ]]; then
		ff=$(($e - 1))
		$vww "$ff" "$2" "$vw"
	elif [[ $ret -eq 1 ]]; then
		killall $vww & exit 1
	elif [[ $B = TRUE ]]; then
		ff=$(($e + 1))
		$vww "$ff" "$2" "$vw"
	else
		$drtu/cls w &
		killall $vww & exit 1
	fi
