#!/bin/bash
# -*- ENCODING: UTF-8 -*-

source /usr/share/idiomind/ifs/c.conf
source $DS/ifs/trans/$lgs/practice.conf
DSP="$DS/addons/Practice/"
strt="$DSP/strt"
IND='play $DSP/all.mp3'
w9="$DC/addons/practice/w9"
w6="$DC/addons/practice/w6"
DF=$DSP/df.sh
DLW=$DSP/dlw.sh
DMC=$DSP/dmc.sh
DLS=$DSP/dls.sh
Wi="$DC_tlt/cnfg3"
Si="$DC_tlt/cnfg4"
Li="$DC_tlt/cnfg1"
cd "$DC_tlt/Practice"

function look() {
		yad --title="$tpc" --borders=5 --center \
		--on-top --skip-taskbar --window-icon=idiomind \
		--center --image=gtk-ok --button=Ok:2 \
		--button="   $restart   ":0 --width=360 --height=120 \
		--text="<b>   $complete\\n   $(cat look_f)</b>\\n\\n"
}

function get_list() {
		if [ "$(cat "$Si" | wc -l)" -gt 0 ]; then
			grep -F -x -v -f "$Si" "$Li" > $1
		else
			cat "$Li" > $1
		fi
}

function get_list2() {

	(
	echo "5" ; sleep 0
	echo "# " ; sleep 0
	n=1
	while [[ $n -le "$(cat mcin | sed 's/mcin//g' | wc -l)" ]]; do
		word=$(sed -n "$n"p mcin)
		file="$DM_tlt/words/$word.mp3"
		echo "$(eyeD3 "$file" | grep -o -P "(?<=IWI2I0I).*(?=IWI2I0I)")" >> word1.idx
		let n++
	done
	) | yad --progress \
	--width 50 --height 35 --undecorated \
	--pulsate --auto-close \
	--skip-taskbar --center --no-buttons

}

function get_list3() {
		if [ "$(cat "$Wi" | wc -l)" -gt 0 ]; then
			grep -F -x -v -f "$Wi" "$Li" > $1
		else
			cat "$Li" > $1
		fi
}

function starting() {
		yad --form --center --borders=5 --image=info \
		--title="Info" --on-top --window-icon=idiomind \
		--button=Ok:1 --skip-taskbar --width=360 --height=120 \
		--text "<span color='#797979'><b>$1</b></span>"
		$strt & killall prct.sh & exit 1
}

if [[ "$1" = f ]]; then

	cd "$DC_tlt/Practice"
	
	if [[ -f look_f ]]; then
		look "look_f"
		ret=$(echo "$?")
		[[ "$ret" -eq 0 ]] && $DSP/cls df & exit || $DSP/strt & exit
	fi

	if ([ -f fin ] && [ -f ok.f ]); then
		grep -F -x -v -f ok.f fin > fin1
		echo "-- recomenzando session"
	else
		get_list fin && cp -f fin fin1
		[[ "$(cat fin  | wc -l)" -lt 4 ]] && starting "$starting1"
		echo "-- nueva session"
	fi
	
	$DF
	
	
elif [[ "$1" = m ]]; then

	cd "$DC_tlt/Practice"
	
	if [[ -f look_mc ]]; then
		look "look_mc"
		ret=$(echo "$?")
		[[ "$ret" -eq 0 ]] && $DSP/cls mc & exit || $DSP/strt & exit
	fi

	if ([ -f mcin ] && [ -f ok.m ]); then
		grep -F -x -v -f ok.m mcin > mcin1
		echo "-- recomenzando session"
		
	else
		get_list mcin && cp -f mcin mcin1
		if [ ! -f word1.idx ]; then
			get_list2
		fi
		[[ "$(cat mcin  | wc -l)" -lt 4 ]] && starting "$starting1"
		 echo "-- nueva session"
	fi

	$DMC
	
	
elif [[ "$1" = w ]]; then

	cd "$DC_tlt/Practice"
	
	if [[ -f look_lw ]]; then
		look "look_lw"
		ret=$(echo "$?")
		[[ "$ret" -eq 0 ]] && $DSP/cls dw & exit || $DSP/strt & exit
	fi

	if ([ -f lwin ] && [ -f ok.w ]); then
		grep -F -x -v -f ok.w lwin > lwin1
		echo "-- recomenzando session"
	else
		get_list lwin && cp -f lwin lwin1
		[[ "$(cat lwin  | wc -l)" -lt 4 ]] && starting "$starting1"
		echo "-- nueva session"
	fi
	
	$DLW
	
	
elif [[ "$1" = s ]]; then

	cd "$DC_tlt/Practice"
	
	if [[ -f look_ls ]]; then
		look "look_ls"
		ret=$(echo "$?")
		[[ "$ret" -eq 0 ]] && $DSP/cls ds & exit || $DSP/strt & exit
	fi

	if ([ -f lsin ] && [ -f ok.s ]); then
		grep -F -x -v -f ok.s lsin > lsin1
		echo "-- recomenzando session"
	else
		get_list3 lsin && cp -f lsin lsin1
		[[ "$(cat lsin  | wc -l)" -lt 1 ]] && starting "$starting2"
		echo "-- nueva session"
	fi
	
	$DLS
	
fi
