#!/bin/bash
# -*- ENCODING: UTF-8 -*-

source /usr/share/idiomind/ifs/c.conf
source $DS/ifs/trans/$lgs/practice.conf
DSP="$DS/addons/Practice/"
strt="$DSP/strt"
IND='play $DSP/all.mp3'
w9="$DC/addons/practice/w9"
w6="$DC/addons/practice/w6"
DF=$DSP/df.sh
DLW=$DSP/dlw.sh
DMC=$DSP/dmc.sh
DLS=$DSP/dls.sh
Wi="$DC_tlt/cnfg3"
Si="$DC_tlt/cnfg4"
Li="$DC_tlt/cnfg1"
cd "$DC_tlt/Practice"

function look() {
		yad --title="$tpc" --borders=5 --center \
		--on-top --skip-taskbar --window-icon=idiomind \
		--center --image=gtk-ok --button=Ok:2 \
		--button="   $restart   ":0 --width=360 --height=120 \
		--text="<b>   $complete\\n   $(cat look_f)</b>\\n\\n"
}

function get_list() {
		if [ "$(cat "$Si" | wc -l)" -gt 0 ]; then
			grep -F -x -v -f "$Si" "$Li" > $1
		else
			cat "$Li" > $1
		fi
}

function get_list2() {

	(
	echo "5" ; sleep 0
	echo "# " ; sleep 0
	n=1
	while [[ $n -le "$(cat mcin | sed 's/mcin//g' | wc -l)" ]]; do
		word=$(sed -n "$n"p mcin)
		file="$DM_tlt/words/$word.mp3"
		echo "$(eyeD3 "$file" | grep -o -P "(?<=IWI2I0I).*(?=IWI2I0I)")" >> word1.idx
		let n++
	done
	) | yad --progress \
	--width 50 --height 35 --undecorated \
	--pulsate --auto-close \
	--skip-taskbar --center --no-buttons

}

function starting() {
		yad --form --center --borders=5 --image=info \
		--title="Info" --on-top --window-icon=idiomind \
		--button=Ok:1 --skip-taskbar --width=360 --height=120 \
		--text "<span color='#797979'><b>$1</b></span>"
		$strt & killall prct.sh & exit 1
}

if [[ "$1" = f ]]; then

	cd "$DC_tlt/Practice"
	
	if [[ -f look_f ]]; then
		look "look_f"
		ret=$(echo "$?")
		[[ "$ret" -eq 0 ]] && $DSP/cls df & exit || $DSP/strt & exit
	fi

	if ([ -f fin ] && [ -f ok.f ]); then
		grep -F -x -v -f ok.f fin > fin1
		echo "-- recomenzando session"
	else
		get_list fin && cp -f fin fin1
		[[ "$(cat fin  | wc -l)" -lt 4 ]] && starting "$starting1"
		echo "-- nueva session"
	fi
	
	$DF
	
	
	
elif [[ "$1" = m ]]; then

	cd "$DC_tlt/Practice"
	
	if [[ -f look_mc ]]; then
		look "look_mc"
		ret=$(echo "$?")
		[[ "$ret" -eq 0 ]] && $DSP/cls mc & exit || $DSP/strt & exit
	fi

	if ([ -f mcin ] && [ -f ok.m ]); then
		grep -F -x -v -f ok.m mcin > mcin1
		echo "-- recomenzando session"
		
	else
		get_list mcin && cp -f mcin mcin1
		if [ ! -f word1.idx ]; then
			get_list2
		fi
		[[ "$(cat mcin  | wc -l)" -lt 4 ]] && starting "$starting1"
		 echo "-- nueva session"
	fi

	$DMC
	
	
	
	

	
elif [[ "$1" = w ]]; then

	cd "$DC_tlt/Practice"
	
	if [[ -f look_lw ]]; then
		look "look_lw"
		ret=$(echo "$?")
		[[ "$ret" -eq 0 ]] && $DSP/cls dw & exit || $DSP/strt & exit
	fi

	if ([ -f lwin ] && [ -f ok.w ]); then
		grep -F -x -v -f ok.w lwin > lwin1
		echo "-- recomenzando session"
	else
		get_list lwin && cp -f lwin lwin1
		[[ "$(cat lwin  | wc -l)" -lt 4 ]] && starting "$starting1"
		echo "-- nueva session"
	fi
	
	$DLW
	
	
	
	
	
	

elif [ "$1" = s ]; then

	cd "$DC_tlt/Practice"
	if [ -f look_ls ]; then
		yad --title="$tpc" --borders=5 --center  \
		--on-top --skip-taskbar --window-icon=idiomind \
		--center --image=gtk-ok \
		--button="   $restart   ":0 --button=Ok:1 \
		--text "<b>   $complete\\n   $(cat look_ls)</b>\\n\\n" \
		--width=360 --height=120
		ret=$?
			if [[ "$ret" -eq 0 ]]; then
				$DSP/cls ds & exit
			else
				$DSP/strt & exit
			fi
	fi
	if [ -f lsin.tmp ]; then
		rm *.ok *.no
		sed '/^$/d' lsin.tmp > lsin
	else
		cd "$DM_tlt"
		cd "$DC_tlt/Practice"
		if [ "$(cat "$Wi" | wc -l)" -gt 0 ]; then
			echo "$(grep -F -x -v -f "$Wi" "$Li" | wc -l)" > idxlsin
			grep -F -x -v -f "$Wi" "$Li" > lsin
		else
			echo "$(cat "$Li" | wc -l)" > idxlsin
			cat "$Li" > lsin
		fi
		rm -f *.id *.ok *.no $DT/*.tp
		if [ "$(cat lsin | wc -l)" -lt 1 ]; then
			yad --form --center --borders=5 --skip-taskbar \
			--title="Info" --on-top --window-icon=idiomind \
			--button=Ok:1 --image=info \
			--text "<span color='#797979'><b>$starting2</b></span>" \
			--width=360 --height=120
			rm -f $DT/text.tmp
			$strt & killall prct & exit
		fi
	fi
	cp -f lsin lsin.tmp
	$DLS 1
	
	[[ ! -f lsin.ok ]] && sed -i '/^$/d' lsin.ok
	[[ ! -f lsin.no ]] && sed -i '/^$/d' lsin.no
	[[ ! -f lsin.1.no ]] && sed -i '/^$/d' lsin.1.no
	echo "$(cat lsin.ok | wc -l)" > ls_r
	
	if ([ -f lsin.no ] || [ -f lsin.1.no ]); then
		[[ -f ls_r ]] && s1=$(cat  ls_r) || s1=1
		s4=$(cat idxlsin)
		var4=$((100*$s1/$s4))
		if [ $var4 -lt 1 ]; then
			echo 1 > .iconls
		elif [ $var4 -lt 5 ]; then
			echo 2 > .iconls
		elif [ $var4 -lt 10 ]; then
			echo 3 > .iconls
		elif [ $var4 -lt 15 ]; then
			echo 4 > .iconls
		elif [ $var4 -lt 20 ]; then
			echo 5 > .iconls
		elif [ $var4 -lt 25 ]; then
			echo 6 > .iconls
		elif [ $var4 -lt 30 ]; then
			echo 7 > .iconls
		elif [ $var4 -lt 35 ]; then
			echo 8 > .iconls
		elif [ $var4 -lt 40 ]; then
			echo 9 > .iconls
		elif [ $var4 -lt 45 ]; then
			echo 10 > .iconls
		elif [ $var4 -lt 50 ]; then
			echo 11 > .iconls
		elif [ $var4 -lt 55 ]; then
			echo 12 > .iconls
		elif [ $var4 -lt 60 ]; then
			echo 13 > .iconls
		elif [ $var4 -lt 65 ]; then
			echo 14 > .iconls
		elif [ $var4 -lt 70 ]; then
			echo 15 > .iconls
		elif [ $var4 -lt 75 ]; then
			echo 16 > .iconls
		elif [ $var4 -lt 80 ]; then
			echo 17 > .iconls
		elif [ $var4 -lt 85 ]; then
			echo 18 > .iconls
		elif [ $var4 -lt 90 ]; then
			echo 19 > .iconls
		elif [ $var4 -lt 95 ]; then
			echo 20 > .iconls
		elif [ $var4 -eq 100 ]; then
			echo 21 > .iconls
		fi
		$strt 8 1
	else
		rm *.ok *.no lsin.tmp lsin
		echo "$(date "+%a %d %B")" > look_ls
		echo 21 > .iconls
		echo ok > .iiconls
		play $DSP/all.mp3 & $strt 4 &
		killall dls.sh
		killall play
		exit 1
	fi
	exit 1
fi
