#!/bin/bash
source /usr/share/idiomind/ifs/c.conf
DS_pp="/usr/share/idiomind/addons/Practice"
eht=$(sed -n 13p $HOME/.config/idiomind/s/cnfg18)
wth=$(sed -n 14p $HOME/.config/idiomind/s/cnfg18)
int="$(sed -n 59p $DS/ifs/trads/$lgs | sed 's/|/\n/g')"
btn="$(sed -n 58p $DS/ifs/trads/$lgs | sed 's/|/\n/g')"

echo "$btn"
/usr/share/idiomind/stop.sh &
cd "$DC_tlt/Practice"

if [[ -n "$1" ]]; then

	if [ $1 = 1 ]; then
		info1="* "
		echo 21 > .iconf
	elif [ $1 = 2 ]; then
		info2="* "
		echo 21 > .iconmc
	elif [ $1 = 3 ]; then
		info3="* "
		echo 21 > .iconlw
	elif [ $1 = 4 ]; then
		info4="* "
		echo 21 > .iconls

	elif [ $1 = 5 ]; then
		easys=$(cat fin.1.ok | wc -l)
		learning=$(cat fin.2.ok| wc -l)
		hards=$(cat fin.$2.no | wc -l)
		learned=$(($(cat f_r)-$easys))
info="<b><big>$learned </big></b><small>$(echo "$int" | sed -n 1p) </small>\\t<span color='#3AB451'><b><big>$easys</big></b></span><small>  $(echo "$int" | sed -n 2p)  </small>\\t<span color='#E78C1E'><b><big>$learning</big></b></span><small>  $(echo "$int" | sed -n 3p) </small>\\t<span color='#D11B5D'><b><big>$hards</big></b></span><small>  $(echo "$int" | sed -n 4p) </small>\\n"
		num=$(cat .iconf)
		info1="* "
	elif [ $1 = 6 ]; then
		easys=$(cat mcin.1.ok | wc -l)
		learning=$(cat mcin.2.ok| wc -l)
		hards=$(cat mcin.$2.no | wc -l)
		learned=$(($(cat mc_r)-$easys))
info="<b><big>$learned </big></b><small>$(echo "$int" | sed -n 1p) </small>\\t<span color='#3AB451'><b><big>$easys</big></b></span><small>  $(echo "$int" | sed -n 2p)  </small>\\t<span color='#E78C1E'><b><big>$learning</big></b></span><small>  $(echo "$int" | sed -n 3p) </small>\\t<span color='#D11B5D'><b><big>$hards</big></b></span><small>  $(echo "$int" | sed -n 4p) </small>\\n"
		num=$(cat .iconmc)
		info2="* "
	elif [ $1 = 7 ]; then
		easys=$(cat lwin.1.ok | wc -l)
		learning=$(cat lwin.2.ok| wc -l)
		hards=$(cat lwin.$2.no | wc -l)
		learned=$(($(cat lw_r)-$easys))
info="<b><big>$learned </big></b><small>$(echo "$int" | sed -n 1p) </small>\\t<span color='#3AB451'><b><big>$easys</big></b></span><small>  $(echo "$int" | sed -n 2p)  </small>\\t<span color='#E78C1E'><b><big>$learning</big></b></span><small>  $(echo "$int" | sed -n 3p) </small>\\t<span color='#D11B5D'><b><big>$hards</big></b></span><small>  $(echo "$int" | sed -n 4p) </small>\\n"
		num=$(cat .iconlw)
		info3="* "

	elif [ $1 = 8 ]; then
		wrong=$(cat lsin.no | wc -l)
		good=$(cat lsin.ok| wc -l)
		learned=$(($(cat ls_r)-$good))
info="<b><big>$learned </big></b><small>$(echo "$int" | sed -n 1p) </small>\\t<span color='#3AB451'><b><big>$easys</big></b></span><small>  $(echo "$int" | sed -n 2p)  </small>\\t<span color='#E78C1E'><b><big>$learning</big></b></span><small>  $(echo "$int" | sed -n 3p) </small>\\t<span color='#D11B5D'><b><big>$hards</big></b></span><small>  $(echo "$int" | sed -n 4p) </small>\\n"
		num=$(cat .iconls)
		info4="* "
	fi
fi

iconf=$(cat .iconf)
iconmc=$(cat .iconmc)
iconlw=$(cat .iconlw)
iconls=$(cat .iconls)
img1=$DS_pp/icons_st/$iconf.png
img2=$DS_pp/icons_st/$iconmc.png
img3=$DS_pp/icons_st/$iconlw.png
img4=$DS_pp/icons_st/$iconls.png

VAR=$(yad --ellipsize=NONE --list --text-align=center \
--on-top --class=idiomind --name=idiomind \
--center --window-icon=idiomind --skip-taskbar \
--image-on-top --buttons-layout=edge $img \
--borders=5 --expand-column=2 \
--width=340 --height=400 --text="$info" \
--no-headers --button=$(echo "$btn" | sed -n 1p):3 \
--button=$(echo "$btn" | sed -n 2p):2 --button=$(echo "$btn" | sed -n 3p):0 \
--title="Practice - $tpc" --column="Pick":IMG \
--column="Action" $img1 "          $info1 Flashcards" $img2 \
"          $info2 Multiple Choisse" \
	$img3 "          $info3 Listening Words" $img4 \
"          $info4 Listening Sentences" )
ret=$?


	if [ $ret -eq 0 ]; then
		echo "prctc.$tpc.prctc" >> \
		$HOME/.config/idiomind/addons/stats/.log &
		
		if echo "$VAR" | grep "Flashcards"; then
			$DS_pp/prct f f && exit 1
		fi
		
		if echo "$VAR" | grep "Multiple Choisse"; then
			$DS_pp/prct m m && exit 1
		fi
		
		if echo "$VAR" | grep "Listening Words"; then
			$DS_pp/prct w w && exit 1
		fi
		
		if echo "$VAR" | grep "Listening Sentences"; then
			$DS_pp/prct s s && exit 1
		fi
	
	elif [ $ret -eq 2 ]; then
		echo "lrnpr.$tpc.lrnpr" >> \
		$HOME/.config/idiomind/addons/stats/.log &
		
		if echo "$VAR" | grep "Flashcards"; then
			$DS_pp/prct l f && exit 1
		fi
		
		if echo "$VAR" | grep "Multiple Choisse"; then
			$DS_pp/prct l m && exit 1
		fi
		
		if echo "$VAR" | grep "Listening Words"; then
			$DS_pp/prct l w && exit 1
		fi
		
		if echo "$VAR" | grep "Listening Sentences"; then
			$DS_pp/prct l s && exit 1
		fi
	
	elif [ $ret -eq 3 ]; then
		(
		echo "#" ;
		cd "$DC_tlt/Practice"
		rm *
		cp -f /usr/share/idiomind/addons/Practice/default/.* "$DC_tlt/Practice"
		) | yad --progress \
		--width 50 --height 35 --center \
		--pulsate --auto-close --no-buttons \
		--sticky --undecorated --skip-taskbar
		/usr/share/idiomind/addons/Practice/strt & exit 1
	else
		/usr/share/idiomind/addons/Practice/stp.sh
		exit 1
	fi
