#!/bin/bash
tpc=$(sed -n 1p ~/.config/idiomind/s/topic.id)
lgtl=$(sed -n 2p ~/.config/idiomind/s/lang)
drtt="$HOME/.idiomind/topics/$lgtl/$tpc/"
drsh="$HOME/.idiomind/topics/$lgtl/.share"
drtu="/usr/share/idiomind/addons/Practice/"
u=$(echo "$(whoami)")
cd "$HOME/.config/idiomind/topics/$lgtl/$tpc/Practice"
DT=/tmp/.idmtp1.$u/idadtmptts
yad=yad
vws=$drtu/vws
nw="$1"
st="$2"
if [ ! -f "$DT/lw" ]; then
	nm=$(sed -n "$3"p lsin)
	if [ -f "$drtt/$nm.mp3" ]; then
		file="$drtt/$nm.mp3"
	fi
	mkdir $DT
	chmod 777 -R $DT
	eyeD3 "$file" > $DT/lw
	echo "$nm" > $DT/ls
fi

S=$(cat $DT/lw | grep -o -P '(?<=ISI1I0I).*(?=ISI1I0I)' | awk '{print tolower($0)}')
tgt=$(cat $DT/lw | grep -o -P '(?<=ISTI'$nw'I0I).*(?=ISTI'$nw'I0I)'| awk '{print tolower($0)}')
src=$(cat $DT/lw | grep -o -P '(?<=ISSI'$nw'I0I).*(?=ISSI'$nw'I0I)')
nm=$(cat $DT/ls)
if [ -z "$tgt" ]; then
	tgt=$(cat $DT/lw | grep -o -P '(?<=ISTI1I0I).*(?=ISTI1I0I)' | awk '{print tolower($0)}')
	src=$(cat $DT/lw | grep -o -P '(?<=ISSI1I0I).*(?=ISSI1I0I)')
	nw=1
fi


B=$(echo "$st" | sed -n 1p) 
if [ "$B" = TRUE ]; then
	aut=--timeout=2
fi
prn=play


itm=$(echo "$tgt")
trgt=$(echo "$S" | sed "s#${tgt}#<b><big><big><big>\
<big> ${tgt} <\/\big><\/\big><\/\big><\/\big><\/\b>#g")
play="play '$drtt/$nm.mp3'"
i=Listen

(
"$prn" "$drsh/$itm.mp3"
) &

vw=$($yad --form --always-print-result \
	--center --separator="\\n" --columns=1 --name=idmnd \
	--width=480 --height=240 --on-top --skip-taskbar \
	--borders=15 --class=idmnd $aut --undecorated \
	--title=" " --buttons-layout=center \
	--text-align=center --window-icon=idiomind \
	--field="Auto":chk "$B" \
	--button="Practice:1" \
	--button="$i:"$play"" \
	--button=">:2" \
	--text="\\n$trgt\\n\\n <i><big><big><big>\
<span color='#7F7F7F'>[ </span> \
<span color='#7B7F84'><b><big> $src </big></b></span> \
<span color='#7F7F7F'> ]</span></big></big></big></i> \\n\\n")

	ret=$?
	if [[ $ret -eq 1 ]]; then 
		killall vws & rm -f -r $DT & exit 1
	elif [[ $ret -eq 2 ]]; then
		ff=$(($nw + 1))
		$vws "$ff" "$vw"
	elif [[ $ret -eq 3 ]]; then
		ff=$(($nw - 1))
		$vws "$ff" "$vw"
	elif [[ $B = TRUE ]]; then 
		ff=$(($nw + 1))
		$vws "$ff" "$vw"
	else
		killall vws &
		$drtu/cls s &
		rm -f -r $DT & exit 1
	fi
