#!/bin/bash

lngt=$(sed -n 2p ~/.config/idiomind/s/lang)

if [ -f "$HOME/.idiomind/topics/$lngt/Feeds/conten/$1.mp3" ]; then
	drtx="$HOME/.idiomind/topics/$lngt/Feeds/conten/"
elif [ -f "$HOME/.idiomind/topics/$lngt/Feeds/kept/$1.mp3" ]; then
	drtx="$HOME/.idiomind/topics/$lngt/Feeds/kept"
fi

sleep 0.5

if [[ "$(ps -A | grep -o "plwd")" = "plwd" ]]; then
	exit 1
else
	if [[ "$(ps -A | grep -o "play")" = "play" ]]; then
		exit 1
	fi
	play "$drtx/$1.mp3" & sleep 0.2 && exit 1
fi

