#!/bin/bash
topic=$(sed -n 1p ~/.config/idiomind/s/cnfg8)
lngt=$(sed -n 2p ~/.config/idiomind/s/cnfg10)
lngs=$(sed -n 2p ~/.config/idiomind/s/cnfg9)
DIR1="$HOME/.idiomind/topics/$lngt/$topic"

sleep 0.5

if [[ "$(ps -A | grep -o "plwd1")" = "plwd1" ]]; then

	exit 1
else

	if [[ "$(ps -A | grep -o "play")" = "play" ]]; then
		exit 1
	fi
	
	play "$DIR1/words/$1.mp3" & sleep 0.2 && exit 1
fi
