#!/bin/bash
topic=$(sed -n 1p ~/.config/idiomind/s/topic.id)
lngt=$(sed -n 2p ~/.config/idiomind/s/lang)
lngs=$(sed -n 2p ~/.config/idiomind/s/langt)
DIR1="$HOME/.idiomind/topics/$lngt/$topic"

sleep 0.5

if [[ "$(ps -A | grep -o "plwd")" = "plwd" ]]; then
exit 1
else

if [[ "$(ps -A | grep -o "play")" = "play" ]]; then
exit 1
fi

play "$DIR1/$1.mp3" & sleep 0.2 && exit 1
fi
exit
