#!/bin/bash
topic=$(sed -n 1p ~/.config/idiomind/s/cnfg8)
lngt=$(sed -n 2p ~/.config/idiomind/s/cnfg9)
lngs=$(sed -n 2p ~/.config/idiomind/s/cnfg10)

if [[ "$(ps -A | grep -o "plst2")" = "plst2" ]]; then
/usr/share/idiomind/audio/plwd2 "$1"
else
/usr/share/idiomind/audio/plst2 "$1"
fi
