#!/bin/bash
DIR1=$HOME/.config/idiomind/s/
sttng4=$(sed -n 1p $DIR1/cnfg3)
sttng5=$(sed -n 2p $DIR1/cnfg3)

if [ -z $sttng4 ]; then
	echo 'FALSE' > $DIR1/cnfg3
	echo ' ' >> $DIR1/cnfg3
	sttng4=$(sed -n 1p $DIR1/cnfg3)
fi

CNFG=$(/lib32/yad_idiomind --center --form --on-top \
	--skip-taskbar --borders=15 --expand-column=3 --no-headers \
	--print-all --button=Close:0 --width=350 --height=250 \
	--always-print-result --editable \
	--title="Google translation service" --window-icon=idiomind \
	--field="Used Google translation service:CHK" "$sttng4" \
	--field="key::TXT" "$sttng5");

		sttng4=$(echo "$CNFG" | cut -d "|" -f1)
		sttng5=$(echo "$CNFG" | cut -d "|" -f2)
		echo "$sttng4" > $DIR1/cnfg3
		echo "$sttng5" >>  $DIR1/cnfg3
		exit

