#!/bin/bash
cd "$HOME/.config/idiomind/addons/Learning with news/Japanese/subscripts"
echo "Nishinippon.co.jp - Sample subscription" > ../.rss
echo "http://www.nishinippon.co.jp/rss/lifestyle" > ../link
