#!/bin/bash
source /usr/share/idiomind/ifs/c.conf
int="$(sed -n 51p $DS/ifs/trads/$lgs | sed 's/|/\n/g')"
btn="$(sed -n 50p $DS/ifs/trads/$lgs | sed 's/|/\n/g')"
itdl="$2"
kpt="$DM_tl/Feeds/kept"
drtc="$DC_tl/Feeds/"

if [[ $1 = dlti ]]; then
	if [ -f "$kpt/words/$itdl.mp3" ]; then

		$yad --title="$(echo "$int" | sed -n 1p)" --width=320 \
		--height=80 --on-top --center \
		--image=dialog-question --skip-taskbar \
		--text=" $(echo "$int" | sed -n 2p)" \
		--window-icon=idiomind --borders=10 \
		--button=gtk-delete:2 --button=$(echo "$btn" | sed -n 1p):0
		ret=$?
		
			if [[ $ret -eq 2 ]]; then
				rm "$kpt/words/$itdl.mp3"
				cd "$drtc"
				grep -v -x -v "$itdl" ./.inx > ./inx
				sed '/^$/d' ./inx > ./.inx
				rm ./inx
				grep -v -x -v "$itdl" ./.winx > ./winx
				sed '/^$/d' ./winx > ./.winx
				rm ./winx
				grep -v -x -v "$itdl" ./.t-inx > ./t-inx
				sed '/^$/d' ./t-inx > ./.t-inx
				rm ./t-inx
				notify-send  -i idiomind "$itdl" "$(echo "$int" | sed -n 3p)"  -t 1500
			fi
			
			if [[ $ret -eq 1 ]]; then
				exit
			fi
	else
		$yad --title="$(echo "$int" | sed -n 1p)" --width=320 \
		--height=80 --on-top --center \
		--image=dialog-question --skip-taskbar \
		--text=" $(echo "$int" | sed -n 4p)" \
		--window-icon=idiomind --borders=10 \
		--button=gtk-delete:2 --button=$(echo "$btn" | sed -n 1p):0
		ret=$?
		
			if [[ $ret -eq 2 ]]; then
				rm "$kpt/$itdl.mp3"
				rm "$kpt/$itdl.lnk"
				cd "$drtc"
				grep -v -x -v "$itdl" ./.inx > ./inx
				sed '/^$/d' ./inx > ./.inx
				rm ./inx
				grep -v -x -v "$itdl" ./.sinx > ./sinx
				sed '/^$/d' ./sinx > ./.sinx
				rm ./sinx
				grep -v -x -v "$itdl" ./.t-inx > ./t-inx
				sed '/^$/d' ./t-inx > ./.t-inx
				rm ./t-inx
				notify-send  -i idiomind "$itdl" "$(echo "$int" | sed -n 3p)"  -t 1500
			fi
			
			if [[ $ret -eq 1 ]]; then
				exit
			fi
	fi

elif [[ $1 = dlns ]]; then
	$yad --width=400 --height=50 --title="$(echo "$int" | sed -n 1p)" \
	--on-top --image=dialog-question --center --geometry=400x50 --skip-taskbar \
	--window-icon=idiomind --text="$(echo "$int" | sed -n 5p)" \
	--borders=5 --button="gtk-delete:0" --button="$(echo "$btn" | sed -n 1p):1"
		ret=$?

		if [[ $ret -eq 0 ]]; then
		
			rm -r $DM_tl/Feeds/conten/*
			rm $DC_tl/Feeds/.updt.lst
			rm $DC_tl/Feeds/.dt
			notify-send  -i idiomind "$(echo "$int" | sed -n 3p)" " " -t 2000
			
		else
			exit 1
		fi

elif [[ $1 = dlkt ]]; then

	$yad --image=dialog-question \
	--window-icon=idiomind --width=360 --height=80  \
	--title="$(echo "$int" | sed -n 1p)" --on-top --center --skip-taskbar \
	--borders=10 --button=gtk-delete:0 --name=idiomind \
	--button=$(echo "$btn" | sed -n 1p):1 --text=" $(echo "$int" | sed -n 6p)"

	ret=$?

	if [[ $ret -eq 0 ]]; then
		rm -r "$drtc"/.inx "$drtc"/.winx "$drtc"/.sinx "$drtc"/.t-inx
		touch "$drtc"/.inx "$drtc"/.winx "$drtc"/.sinx "$drtc"/.t-inx
		rm -r "$kpt"/*.mp3
		rm -r "$kpt"/words/*.mp3
	else
		exit 1
	fi

fi
